export const mediumPuzzles = {
  "3-4-6-7-8-38": {
    bigNumber: 38,
    tiles: [6, 7, 4, 8, 3],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [6, 3, 8, 28],
      },
      {
        tile1: 6,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [8, 28, 18],
      },
      {
        tile1: 18,
        symbol: "subtract",
        tile2: 8,
        remainingTiles: [28, 10],
      },
      { tile1: 10, symbol: "add", tile2: 28, remainingTiles: [38] },
    ],
  },
  "1-2-2-5-9-1": {
    bigNumber: 1,
    tiles: [1, 2, 2, 9, 5],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 1,
        symbol: "add",
        tile2: 5,
        remainingTiles: [9, 2, 2, 6],
      },
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 6,
        remainingTiles: [9, 2, 12],
      },
      { tile1: 9, symbol: "add", tile2: 2, remainingTiles: [12, 11] },
      { tile1: 12, symbol: "subtract", tile2: 11, remainingTiles: [1] },
    ],
  },
  "3-7-9-9-9-90": {
    bigNumber: 90,
    tiles: [7, 3, 9, 9, 9],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 9,
        symbol: "divide",
        tile2: 9,
        remainingTiles: [3, 9, 7, 1],
      },
      { tile1: 3, symbol: "add", tile2: 7, remainingTiles: [9, 1, 10] },
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [10, 9],
      },
      { tile1: 10, symbol: "multiply", tile2: 9, remainingTiles: [90] },
    ],
  },
  "1-5-8-8-9-30": {
    bigNumber: 30,
    tiles: [5, 9, 8, 8, 1],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 5,
        remainingTiles: [8, 9, 8, 5],
      },
      { tile1: 8, symbol: "add", tile2: 5, remainingTiles: [8, 9, 13] },
      { tile1: 9, symbol: "add", tile2: 8, remainingTiles: [13, 17] },
      { tile1: 17, symbol: "add", tile2: 13, remainingTiles: [30] },
    ],
  },
  "2-6-8-8-8-4": {
    bigNumber: 4,
    tiles: [8, 8, 2, 8, 6],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 8,
        symbol: "multiply",
        tile2: 6,
        remainingTiles: [8, 8, 2, 48],
      },
      {
        tile1: 2,
        symbol: "add",
        tile2: 8,
        remainingTiles: [8, 48, 10],
      },
      {
        tile1: 48,
        symbol: "subtract",
        tile2: 8,
        remainingTiles: [10, 40],
      },
      { tile1: 40, symbol: "divide", tile2: 10, remainingTiles: [4] },
    ],
  },
  "1-1-6-9-9-3": {
    bigNumber: 3,
    tiles: [1, 1, 9, 9, 6],
    symbols: { add: 0, subtract: 1, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 9,
        symbol: "subtract",
        tile2: 6,
        remainingTiles: [1, 9, 1, 3],
      },
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [1, 9, 3],
      },
      {
        tile1: 9,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [3, 9],
      },
      { tile1: 9, symbol: "divide", tile2: 3, remainingTiles: [3] },
    ],
  },
  "2-7-8-8-9-95": {
    bigNumber: 95,
    tiles: [8, 2, 8, 9, 7],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 8,
        symbol: "multiply",
        tile2: 8,
        remainingTiles: [9, 2, 7, 64],
      },
      {
        tile1: 64,
        symbol: "divide",
        tile2: 2,
        remainingTiles: [9, 7, 32],
      },
      {
        tile1: 9,
        symbol: "multiply",
        tile2: 7,
        remainingTiles: [32, 63],
      },
      { tile1: 63, symbol: "add", tile2: 32, remainingTiles: [95] },
    ],
  },
  "4-4-7-7-9-40": {
    bigNumber: 40,
    tiles: [9, 4, 4, 7, 7],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 4,
        symbol: "multiply",
        tile2: 7,
        remainingTiles: [4, 7, 9, 28],
      },
      {
        tile1: 9,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [7, 28, 5],
      },
      { tile1: 5, symbol: "add", tile2: 28, remainingTiles: [7, 33] },
      { tile1: 33, symbol: "add", tile2: 7, remainingTiles: [40] },
    ],
  },
  "1-3-3-9-9-72": {
    bigNumber: 72,
    tiles: [9, 9, 3, 1, 3],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 3,
        symbol: "subtract",
        tile2: 1,
        remainingTiles: [3, 9, 9, 2],
      },
      { tile1: 9, symbol: "add", tile2: 2, remainingTiles: [3, 9, 11] },
      {
        tile1: 11,
        symbol: "subtract",
        tile2: 3,
        remainingTiles: [9, 8],
      },
      { tile1: 9, symbol: "multiply", tile2: 8, remainingTiles: [72] },
    ],
  },
  "1-4-6-6-9-86": {
    bigNumber: 86,
    tiles: [6, 6, 1, 9, 4],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 4,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [9, 6, 6, 4],
      },
      { tile1: 9, symbol: "add", tile2: 6, remainingTiles: [6, 4, 15] },
      {
        tile1: 6,
        symbol: "multiply",
        tile2: 15,
        remainingTiles: [4, 90],
      },
      { tile1: 90, symbol: "subtract", tile2: 4, remainingTiles: [86] },
    ],
  },
  "3-3-3-8-8-3": {
    bigNumber: 3,
    tiles: [3, 3, 8, 3, 8],
    symbols: { add: 2, subtract: 2, multiply: 0, divide: 0 },
    solution: [
      {
        tile1: 3,
        symbol: "add",
        tile2: 3,
        remainingTiles: [3, 8, 8, 6],
      },
      { tile1: 6, symbol: "add", tile2: 8, remainingTiles: [3, 8, 14] },
      {
        tile1: 14,
        symbol: "subtract",
        tile2: 8,
        remainingTiles: [3, 6],
      },
      { tile1: 6, symbol: "subtract", tile2: 3, remainingTiles: [3] },
    ],
  },
  "2-3-8-9-9-16": {
    bigNumber: 16,
    tiles: [9, 3, 2, 8, 9],
    symbols: { add: 3, subtract: 0, multiply: 0, divide: 1 },
    solution: [
      {
        tile1: 9,
        symbol: "add",
        tile2: 9,
        remainingTiles: [3, 8, 2, 18],
      },
      {
        tile1: 18,
        symbol: "divide",
        tile2: 3,
        remainingTiles: [8, 2, 6],
      },
      { tile1: 8, symbol: "add", tile2: 2, remainingTiles: [6, 10] },
      { tile1: 10, symbol: "add", tile2: 6, remainingTiles: [16] },
    ],
  },
  "1-4-5-7-9-48": {
    bigNumber: 48,
    tiles: [5, 9, 7, 4, 1],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 4,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [5, 7, 1, 36],
      },
      {
        tile1: 36,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [5, 7, 36],
      },
      { tile1: 7, symbol: "add", tile2: 36, remainingTiles: [5, 43] },
      { tile1: 43, symbol: "add", tile2: 5, remainingTiles: [48] },
    ],
  },
  "2-3-4-5-6-6": {
    bigNumber: 6,
    tiles: [5, 2, 6, 4, 3],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 5,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [2, 3, 6, 1],
      },
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [2, 6, 3],
      },
      { tile1: 6, symbol: "divide", tile2: 2, remainingTiles: [3, 3] },
      { tile1: 3, symbol: "add", tile2: 3, remainingTiles: [6] },
    ],
  },
  "1-1-2-4-7-5": {
    bigNumber: 5,
    tiles: [2, 7, 1, 1, 4],
    symbols: { add: 0, subtract: 2, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 2,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [1, 7, 4, 2],
      },
      {
        tile1: 4,
        symbol: "subtract",
        tile2: 2,
        remainingTiles: [1, 7, 2],
      },
      {
        tile1: 7,
        symbol: "subtract",
        tile2: 2,
        remainingTiles: [1, 5],
      },
      { tile1: 5, symbol: "multiply", tile2: 1, remainingTiles: [5] },
    ],
  },
  "2-5-6-7-8-59": {
    bigNumber: 59,
    tiles: [5, 6, 7, 8, 2],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 7,
        symbol: "add",
        tile2: 2,
        remainingTiles: [8, 6, 5, 9],
      },
      {
        tile1: 9,
        symbol: "multiply",
        tile2: 5,
        remainingTiles: [8, 6, 45],
      },
      { tile1: 6, symbol: "add", tile2: 8, remainingTiles: [45, 14] },
      { tile1: 14, symbol: "add", tile2: 45, remainingTiles: [59] },
    ],
  },
  "2-6-8-8-9-52": {
    bigNumber: 52,
    tiles: [8, 9, 6, 2, 8],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 8,
        symbol: "add",
        tile2: 9,
        remainingTiles: [8, 2, 6, 17],
      },
      {
        tile1: 17,
        symbol: "subtract",
        tile2: 8,
        remainingTiles: [2, 6, 9],
      },
      {
        tile1: 6,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [2, 54],
      },
      { tile1: 54, symbol: "subtract", tile2: 2, remainingTiles: [52] },
    ],
  },
  "1-3-4-5-9-26": {
    bigNumber: 26,
    tiles: [5, 1, 3, 9, 4],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 3,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [4, 5, 9, 3],
      },
      { tile1: 9, symbol: "add", tile2: 5, remainingTiles: [4, 3, 14] },
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [14, 12],
      },
      { tile1: 14, symbol: "add", tile2: 12, remainingTiles: [26] },
    ],
  },
  "3-3-6-7-8-9": {
    bigNumber: 9,
    tiles: [6, 7, 3, 8, 3],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 6,
        remainingTiles: [3, 8, 3, 42],
      },
      {
        tile1: 3,
        symbol: "add",
        tile2: 42,
        remainingTiles: [8, 3, 45],
      },
      {
        tile1: 8,
        symbol: "subtract",
        tile2: 3,
        remainingTiles: [45, 5],
      },
      { tile1: 45, symbol: "divide", tile2: 5, remainingTiles: [9] },
    ],
  },
  "3-5-5-5-8-10": {
    bigNumber: 10,
    tiles: [5, 5, 3, 8, 5],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 5,
        symbol: "divide",
        tile2: 5,
        remainingTiles: [5, 8, 3, 1],
      },
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 5,
        remainingTiles: [8, 3, 5],
      },
      { tile1: 8, symbol: "add", tile2: 5, remainingTiles: [3, 13] },
      { tile1: 13, symbol: "subtract", tile2: 3, remainingTiles: [10] },
    ],
  },
  "1-2-4-5-6-5": {
    bigNumber: 5,
    tiles: [6, 5, 4, 1, 2],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 5,
        symbol: "add",
        tile2: 2,
        remainingTiles: [1, 4, 6, 7],
      },
      {
        tile1: 6,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [1, 7, 2],
      },
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [7, 2],
      },
      { tile1: 7, symbol: "subtract", tile2: 2, remainingTiles: [5] },
    ],
  },
  "1-3-4-6-7-64": {
    bigNumber: 64,
    tiles: [7, 1, 4, 6, 3],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 6,
        symbol: "add",
        tile2: 3,
        remainingTiles: [4, 7, 1, 9],
      },
      {
        tile1: 4,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [7, 9, 4],
      },
      { tile1: 7, symbol: "add", tile2: 9, remainingTiles: [4, 16] },
      { tile1: 16, symbol: "multiply", tile2: 4, remainingTiles: [64] },
    ],
  },
  "1-2-2-4-7-6": {
    bigNumber: 6,
    tiles: [2, 7, 4, 2, 1],
    symbols: { add: 0, subtract: 1, multiply: 1, divide: 2 },
    solution: [
      {
        tile1: 4,
        symbol: "divide",
        tile2: 2,
        remainingTiles: [7, 2, 1, 2],
      },
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [7, 2, 2],
      },
      { tile1: 2, symbol: "divide", tile2: 2, remainingTiles: [7, 1] },
      { tile1: 7, symbol: "subtract", tile2: 1, remainingTiles: [6] },
    ],
  },
  "1-2-3-6-9-48": {
    bigNumber: 48,
    tiles: [6, 2, 9, 3, 1],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 6,
        symbol: "subtract",
        tile2: 2,
        remainingTiles: [3, 1, 9, 4],
      },
      { tile1: 9, symbol: "add", tile2: 3, remainingTiles: [1, 4, 12] },
      {
        tile1: 12,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [4, 12],
      },
      { tile1: 12, symbol: "multiply", tile2: 4, remainingTiles: [48] },
    ],
  },
  "1-1-3-6-9-5": {
    bigNumber: 5,
    tiles: [3, 1, 1, 9, 6],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 3,
        symbol: "add",
        tile2: 9,
        remainingTiles: [1, 6, 1, 12],
      },
      {
        tile1: 12,
        symbol: "subtract",
        tile2: 6,
        remainingTiles: [1, 1, 6],
      },
      {
        tile1: 6,
        symbol: "subtract",
        tile2: 1,
        remainingTiles: [1, 5],
      },
      { tile1: 1, symbol: "multiply", tile2: 5, remainingTiles: [5] },
    ],
  },
  "2-4-6-9-9-30": {
    bigNumber: 30,
    tiles: [2, 9, 6, 4, 9],
    symbols: { add: 0, subtract: 2, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 6,
        symbol: "divide",
        tile2: 2,
        remainingTiles: [9, 9, 4, 3],
      },
      {
        tile1: 9,
        symbol: "subtract",
        tile2: 3,
        remainingTiles: [9, 4, 6],
      },
      {
        tile1: 4,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [6, 36],
      },
      { tile1: 36, symbol: "subtract", tile2: 6, remainingTiles: [30] },
    ],
  },
  "1-1-4-7-7-41": {
    bigNumber: 41,
    tiles: [4, 1, 7, 1, 7],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 1,
        symbol: "add",
        tile2: 1,
        remainingTiles: [4, 7, 7, 2],
      },
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 7,
        remainingTiles: [4, 2, 49],
      },
      {
        tile1: 4,
        symbol: "multiply",
        tile2: 2,
        remainingTiles: [49, 8],
      },
      { tile1: 49, symbol: "subtract", tile2: 8, remainingTiles: [41] },
    ],
  },
  "1-1-6-8-9-79": {
    bigNumber: 79,
    tiles: [6, 1, 8, 1, 9],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 9,
        symbol: "multiply",
        tile2: 8,
        remainingTiles: [6, 1, 1, 72],
      },
      { tile1: 1, symbol: "add", tile2: 6, remainingTiles: [1, 72, 7] },
      { tile1: 7, symbol: "add", tile2: 72, remainingTiles: [1, 79] },
      { tile1: 79, symbol: "divide", tile2: 1, remainingTiles: [79] },
    ],
  },
  "2-5-5-6-9-46": {
    bigNumber: 46,
    tiles: [5, 5, 9, 2, 6],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 9,
        symbol: "subtract",
        tile2: 2,
        remainingTiles: [6, 5, 5, 7],
      },
      { tile1: 5, symbol: "add", tile2: 6, remainingTiles: [5, 7, 11] },
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 5,
        remainingTiles: [11, 35],
      },
      { tile1: 35, symbol: "add", tile2: 11, remainingTiles: [46] },
    ],
  },
  "1-2-4-5-8-4": {
    bigNumber: 4,
    tiles: [5, 8, 1, 2, 4],
    symbols: { add: 0, subtract: 1, multiply: 1, divide: 2 },
    solution: [
      {
        tile1: 2,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [8, 5, 4, 2],
      },
      {
        tile1: 4,
        symbol: "multiply",
        tile2: 2,
        remainingTiles: [8, 5, 8],
      },
      { tile1: 8, symbol: "divide", tile2: 8, remainingTiles: [5, 1] },
      { tile1: 5, symbol: "subtract", tile2: 1, remainingTiles: [4] },
    ],
  },
  "3-4-6-8-9-64": {
    bigNumber: 64,
    tiles: [3, 4, 8, 9, 6],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 8,
        symbol: "multiply",
        tile2: 6,
        remainingTiles: [4, 9, 3, 48],
      },
      {
        tile1: 3,
        symbol: "add",
        tile2: 48,
        remainingTiles: [4, 9, 51],
      },
      { tile1: 51, symbol: "add", tile2: 9, remainingTiles: [4, 60] },
      { tile1: 60, symbol: "add", tile2: 4, remainingTiles: [64] },
    ],
  },
  "1-4-6-8-8-2": {
    bigNumber: 2,
    tiles: [4, 1, 8, 6, 8],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 8,
        symbol: "subtract",
        tile2: 1,
        remainingTiles: [6, 8, 4, 7],
      },
      {
        tile1: 4,
        symbol: "multiply",
        tile2: 7,
        remainingTiles: [6, 8, 28],
      },
      { tile1: 8, symbol: "add", tile2: 6, remainingTiles: [28, 14] },
      { tile1: 28, symbol: "divide", tile2: 14, remainingTiles: [2] },
    ],
  },
  "3-4-6-7-8-1": {
    bigNumber: 1,
    tiles: [3, 8, 6, 4, 7],
    symbols: { add: 0, subtract: 2, multiply: 0, divide: 2 },
    solution: [
      {
        tile1: 7,
        symbol: "subtract",
        tile2: 3,
        remainingTiles: [4, 6, 8, 4],
      },
      {
        tile1: 8,
        symbol: "divide",
        tile2: 4,
        remainingTiles: [4, 6, 2],
      },
      {
        tile1: 6,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [2, 2],
      },
      { tile1: 2, symbol: "divide", tile2: 2, remainingTiles: [1] },
    ],
  },
  "1-5-5-7-8-5": {
    bigNumber: 5,
    tiles: [1, 5, 8, 5, 7],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [8, 7, 5, 5],
      },
      {
        tile1: 8,
        symbol: "subtract",
        tile2: 5,
        remainingTiles: [7, 5, 3],
      },
      {
        tile1: 7,
        symbol: "subtract",
        tile2: 5,
        remainingTiles: [3, 2],
      },
      { tile1: 2, symbol: "add", tile2: 3, remainingTiles: [5] },
    ],
  },
  "1-3-7-8-8-36": {
    bigNumber: 36,
    tiles: [3, 7, 8, 8, 1],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [8, 1, 8, 21],
      },
      {
        tile1: 8,
        symbol: "subtract",
        tile2: 1,
        remainingTiles: [8, 21, 7],
      },
      { tile1: 7, symbol: "add", tile2: 8, remainingTiles: [21, 15] },
      { tile1: 21, symbol: "add", tile2: 15, remainingTiles: [36] },
    ],
  },
  "4-4-6-7-9-22": {
    bigNumber: 22,
    tiles: [4, 7, 4, 6, 9],
    symbols: { add: 2, subtract: 0, multiply: 0, divide: 2 },
    solution: [
      {
        tile1: 4,
        symbol: "divide",
        tile2: 4,
        remainingTiles: [9, 6, 7, 1],
      },
      {
        tile1: 7,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [9, 6, 7],
      },
      { tile1: 6, symbol: "add", tile2: 9, remainingTiles: [7, 15] },
      { tile1: 7, symbol: "add", tile2: 15, remainingTiles: [22] },
    ],
  },
  "2-4-4-5-5-12": {
    bigNumber: 12,
    tiles: [5, 5, 4, 4, 2],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 5,
        remainingTiles: [5, 4, 4, 10],
      },
      {
        tile1: 10,
        symbol: "divide",
        tile2: 5,
        remainingTiles: [4, 4, 2],
      },
      {
        tile1: 4,
        symbol: "multiply",
        tile2: 2,
        remainingTiles: [4, 8],
      },
      { tile1: 4, symbol: "add", tile2: 8, remainingTiles: [12] },
    ],
  },
  "1-3-3-5-5-23": {
    bigNumber: 23,
    tiles: [5, 3, 1, 5, 3],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 5,
        remainingTiles: [3, 3, 5, 5],
      },
      { tile1: 5, symbol: "add", tile2: 3, remainingTiles: [3, 5, 8] },
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [8, 15],
      },
      { tile1: 8, symbol: "add", tile2: 15, remainingTiles: [23] },
    ],
  },
  "2-2-4-7-8-14": {
    bigNumber: 14,
    tiles: [8, 7, 2, 2, 4],
    symbols: { add: 0, subtract: 1, multiply: 1, divide: 2 },
    solution: [
      {
        tile1: 8,
        symbol: "divide",
        tile2: 2,
        remainingTiles: [7, 2, 4, 4],
      },
      {
        tile1: 4,
        symbol: "subtract",
        tile2: 2,
        remainingTiles: [7, 4, 2],
      },
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [2, 28],
      },
      { tile1: 28, symbol: "divide", tile2: 2, remainingTiles: [14] },
    ],
  },
  "4-5-5-7-8-34": {
    bigNumber: 34,
    tiles: [7, 4, 8, 5, 5],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 8,
        remainingTiles: [5, 4, 7, 40],
      },
      {
        tile1: 40,
        symbol: "add",
        tile2: 5,
        remainingTiles: [4, 7, 45],
      },
      { tile1: 4, symbol: "add", tile2: 7, remainingTiles: [45, 11] },
      { tile1: 45, symbol: "subtract", tile2: 11, remainingTiles: [34] },
    ],
  },
  "1-1-2-2-9-8": {
    bigNumber: 8,
    tiles: [2, 1, 9, 2, 1],
    symbols: { add: 0, subtract: 1, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 2,
        symbol: "divide",
        tile2: 2,
        remainingTiles: [9, 1, 1, 1],
      },
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [9, 1, 1],
      },
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [1, 9],
      },
      { tile1: 9, symbol: "subtract", tile2: 1, remainingTiles: [8] },
    ],
  },
  "2-2-3-3-7-5": {
    bigNumber: 5,
    tiles: [3, 2, 7, 2, 3],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 2,
        remainingTiles: [3, 2, 3, 14],
      },
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 2,
        remainingTiles: [3, 14, 6],
      },
      { tile1: 6, symbol: "add", tile2: 3, remainingTiles: [14, 9] },
      { tile1: 14, symbol: "subtract", tile2: 9, remainingTiles: [5] },
    ],
  },
  "2-2-5-5-8-52": {
    bigNumber: 52,
    tiles: [2, 8, 2, 5, 5],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 8,
        symbol: "multiply",
        tile2: 5,
        remainingTiles: [5, 2, 2, 40],
      },
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 5,
        remainingTiles: [2, 40, 10],
      },
      { tile1: 40, symbol: "add", tile2: 10, remainingTiles: [2, 50] },
      { tile1: 50, symbol: "add", tile2: 2, remainingTiles: [52] },
    ],
  },
  "2-2-4-5-8-5": {
    bigNumber: 5,
    tiles: [4, 2, 2, 5, 8],
    symbols: { add: 2, subtract: 2, multiply: 0, divide: 0 },
    solution: [
      {
        tile1: 2,
        symbol: "add",
        tile2: 4,
        remainingTiles: [5, 8, 2, 6],
      },
      { tile1: 6, symbol: "add", tile2: 5, remainingTiles: [8, 2, 11] },
      {
        tile1: 8,
        symbol: "subtract",
        tile2: 2,
        remainingTiles: [11, 6],
      },
      { tile1: 11, symbol: "subtract", tile2: 6, remainingTiles: [5] },
    ],
  },
  "5-5-5-9-9-14": {
    bigNumber: 14,
    tiles: [9, 9, 5, 5, 5],
    symbols: { add: 2, subtract: 1, multiply: 0, divide: 1 },
    solution: [
      {
        tile1: 9,
        symbol: "subtract",
        tile2: 5,
        remainingTiles: [5, 9, 5, 4],
      },
      {
        tile1: 5,
        symbol: "divide",
        tile2: 5,
        remainingTiles: [9, 4, 1],
      },
      { tile1: 4, symbol: "add", tile2: 1, remainingTiles: [9, 5] },
      { tile1: 9, symbol: "add", tile2: 5, remainingTiles: [14] },
    ],
  },
  "2-5-5-8-9-38": {
    bigNumber: 38,
    tiles: [5, 9, 5, 8, 2],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 5,
        remainingTiles: [8, 2, 9, 25],
      },
      {
        tile1: 8,
        symbol: "divide",
        tile2: 2,
        remainingTiles: [9, 25, 4],
      },
      { tile1: 25, symbol: "add", tile2: 9, remainingTiles: [4, 34] },
      { tile1: 34, symbol: "add", tile2: 4, remainingTiles: [38] },
    ],
  },
  "3-5-6-6-9-3": {
    bigNumber: 3,
    tiles: [6, 9, 5, 6, 3],
    symbols: { add: 0, subtract: 2, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 6,
        symbol: "subtract",
        tile2: 3,
        remainingTiles: [5, 6, 9, 3],
      },
      {
        tile1: 6,
        symbol: "subtract",
        tile2: 5,
        remainingTiles: [9, 3, 1],
      },
      { tile1: 9, symbol: "divide", tile2: 3, remainingTiles: [1, 3] },
      { tile1: 3, symbol: "multiply", tile2: 1, remainingTiles: [3] },
    ],
  },
  "3-3-3-4-6-5": {
    bigNumber: 5,
    tiles: [6, 3, 3, 3, 4],
    symbols: { add: 1, subtract: 1, multiply: 0, divide: 2 },
    solution: [
      {
        tile1: 4,
        symbol: "add",
        tile2: 6,
        remainingTiles: [3, 3, 3, 10],
      },
      {
        tile1: 3,
        symbol: "divide",
        tile2: 3,
        remainingTiles: [3, 10, 1],
      },
      {
        tile1: 3,
        symbol: "subtract",
        tile2: 1,
        remainingTiles: [10, 2],
      },
      { tile1: 10, symbol: "divide", tile2: 2, remainingTiles: [5] },
    ],
  },
  "1-3-5-5-7-69": {
    bigNumber: 69,
    tiles: [1, 3, 5, 7, 5],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 1,
        symbol: "add",
        tile2: 7,
        remainingTiles: [5, 3, 5, 8],
      },
      { tile1: 3, symbol: "add", tile2: 5, remainingTiles: [5, 8, 8] },
      {
        tile1: 8,
        symbol: "multiply",
        tile2: 8,
        remainingTiles: [5, 64],
      },
      { tile1: 64, symbol: "add", tile2: 5, remainingTiles: [69] },
    ],
  },
  "3-3-6-7-8-76": {
    bigNumber: 76,
    tiles: [6, 3, 7, 3, 8],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 8,
        symbol: "add",
        tile2: 3,
        remainingTiles: [3, 6, 7, 11],
      },
      {
        tile1: 6,
        symbol: "multiply",
        tile2: 11,
        remainingTiles: [3, 7, 66],
      },
      { tile1: 66, symbol: "add", tile2: 7, remainingTiles: [3, 73] },
      { tile1: 73, symbol: "add", tile2: 3, remainingTiles: [76] },
    ],
  },
  "2-3-3-3-4-2": {
    bigNumber: 2,
    tiles: [2, 3, 3, 3, 4],
    symbols: { add: 0, subtract: 1, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 4,
        symbol: "subtract",
        tile2: 3,
        remainingTiles: [2, 3, 3, 1],
      },
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [3, 1, 6],
      },
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [6, 3],
      },
      { tile1: 6, symbol: "divide", tile2: 3, remainingTiles: [2] },
    ],
  },
  "3-4-5-7-8-4": {
    bigNumber: 4,
    tiles: [5, 4, 8, 7, 3],
    symbols: { add: 1, subtract: 2, multiply: 0, divide: 1 },
    solution: [
      {
        tile1: 7,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [5, 8, 3, 3],
      },
      {
        tile1: 8,
        symbol: "subtract",
        tile2: 5,
        remainingTiles: [3, 3, 3],
      },
      { tile1: 3, symbol: "divide", tile2: 3, remainingTiles: [3, 1] },
      { tile1: 3, symbol: "add", tile2: 1, remainingTiles: [4] },
    ],
  },
  "2-5-5-8-8-67": {
    bigNumber: 67,
    tiles: [8, 5, 5, 8, 2],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 8,
        symbol: "multiply",
        tile2: 5,
        remainingTiles: [8, 2, 5, 40],
      },
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 40,
        remainingTiles: [8, 5, 80],
      },
      { tile1: 5, symbol: "add", tile2: 8, remainingTiles: [80, 13] },
      { tile1: 80, symbol: "subtract", tile2: 13, remainingTiles: [67] },
    ],
  },
  "2-3-5-6-9-10": {
    bigNumber: 10,
    tiles: [2, 3, 9, 6, 5],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [6, 2, 3, 45],
      },
      { tile1: 6, symbol: "add", tile2: 3, remainingTiles: [2, 45, 9] },
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 45,
        remainingTiles: [9, 90],
      },
      { tile1: 90, symbol: "divide", tile2: 9, remainingTiles: [10] },
    ],
  },
  "1-8-8-8-9-1": {
    bigNumber: 1,
    tiles: [1, 8, 9, 8, 8],
    symbols: { add: 0, subtract: 1, multiply: 0, divide: 3 },
    solution: [
      {
        tile1: 8,
        symbol: "divide",
        tile2: 8,
        remainingTiles: [1, 8, 9, 1],
      },
      {
        tile1: 1,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [8, 9, 1],
      },
      { tile1: 8, symbol: "divide", tile2: 1, remainingTiles: [9, 8] },
      { tile1: 9, symbol: "subtract", tile2: 8, remainingTiles: [1] },
    ],
  },
  "1-1-4-6-8-80": {
    bigNumber: 80,
    tiles: [8, 1, 1, 4, 6],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 8,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [1, 6, 4, 8],
      },
      { tile1: 6, symbol: "add", tile2: 4, remainingTiles: [1, 8, 10] },
      {
        tile1: 10,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [8, 10],
      },
      { tile1: 10, symbol: "multiply", tile2: 8, remainingTiles: [80] },
    ],
  },
  "2-4-5-6-8-55": {
    bigNumber: 55,
    tiles: [4, 8, 6, 5, 2],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 6,
        symbol: "multiply",
        tile2: 8,
        remainingTiles: [5, 4, 2, 48],
      },
      {
        tile1: 5,
        symbol: "subtract",
        tile2: 2,
        remainingTiles: [4, 48, 3],
      },
      { tile1: 48, symbol: "add", tile2: 3, remainingTiles: [4, 51] },
      { tile1: 51, symbol: "add", tile2: 4, remainingTiles: [55] },
    ],
  },
  "1-1-2-4-9-54": {
    bigNumber: 54,
    tiles: [2, 1, 4, 9, 1],
    symbols: { add: 1, subtract: 0, multiply: 3, divide: 0 },
    solution: [
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [9, 2, 1, 4],
      },
      {
        tile1: 9,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [2, 4, 9],
      },
      { tile1: 2, symbol: "add", tile2: 4, remainingTiles: [9, 6] },
      { tile1: 9, symbol: "multiply", tile2: 6, remainingTiles: [54] },
    ],
  },
  "1-4-6-6-8-11": {
    bigNumber: 11,
    tiles: [8, 6, 6, 1, 4],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 6,
        remainingTiles: [6, 4, 8, 6],
      },
      { tile1: 4, symbol: "add", tile2: 8, remainingTiles: [6, 6, 12] },
      { tile1: 6, symbol: "divide", tile2: 6, remainingTiles: [12, 1] },
      { tile1: 12, symbol: "subtract", tile2: 1, remainingTiles: [11] },
    ],
  },
  "2-2-4-5-9-41": {
    bigNumber: 41,
    tiles: [5, 2, 9, 4, 2],
    symbols: { add: 0, subtract: 1, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [2, 4, 2, 45],
      },
      {
        tile1: 4,
        symbol: "multiply",
        tile2: 2,
        remainingTiles: [2, 45, 8],
      },
      { tile1: 8, symbol: "divide", tile2: 2, remainingTiles: [45, 4] },
      { tile1: 45, symbol: "subtract", tile2: 4, remainingTiles: [41] },
    ],
  },
  "1-1-7-7-8-8": {
    bigNumber: 8,
    tiles: [7, 1, 7, 1, 8],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 8,
        symbol: "subtract",
        tile2: 7,
        remainingTiles: [1, 1, 7, 1],
      },
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [1, 7, 1],
      },
      { tile1: 1, symbol: "divide", tile2: 1, remainingTiles: [7, 1] },
      { tile1: 1, symbol: "add", tile2: 7, remainingTiles: [8] },
    ],
  },
  "3-5-6-7-9-43": {
    bigNumber: 43,
    tiles: [6, 3, 7, 9, 5],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 6,
        remainingTiles: [9, 7, 3, 30],
      },
      {
        tile1: 30,
        symbol: "subtract",
        tile2: 3,
        remainingTiles: [9, 7, 27],
      },
      { tile1: 9, symbol: "add", tile2: 7, remainingTiles: [27, 16] },
      { tile1: 16, symbol: "add", tile2: 27, remainingTiles: [43] },
    ],
  },
  "2-2-3-8-8-68": {
    bigNumber: 68,
    tiles: [3, 8, 2, 8, 2],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 8,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [2, 8, 2, 24],
      },
      {
        tile1: 24,
        symbol: "add",
        tile2: 2,
        remainingTiles: [8, 2, 26],
      },
      { tile1: 8, symbol: "add", tile2: 26, remainingTiles: [2, 34] },
      { tile1: 34, symbol: "multiply", tile2: 2, remainingTiles: [68] },
    ],
  },
  "3-3-5-6-8-15": {
    bigNumber: 15,
    tiles: [5, 6, 8, 3, 3],
    symbols: { add: 2, subtract: 2, multiply: 0, divide: 0 },
    solution: [
      {
        tile1: 8,
        symbol: "add",
        tile2: 6,
        remainingTiles: [3, 5, 3, 14],
      },
      {
        tile1: 3,
        symbol: "add",
        tile2: 14,
        remainingTiles: [5, 3, 17],
      },
      {
        tile1: 5,
        symbol: "subtract",
        tile2: 3,
        remainingTiles: [17, 2],
      },
      { tile1: 17, symbol: "subtract", tile2: 2, remainingTiles: [15] },
    ],
  },
  "1-7-7-7-9-16": {
    bigNumber: 16,
    tiles: [7, 7, 1, 7, 9],
    symbols: { add: 1, subtract: 0, multiply: 1, divide: 2 },
    solution: [
      {
        tile1: 9,
        symbol: "add",
        tile2: 7,
        remainingTiles: [7, 7, 1, 16],
      },
      {
        tile1: 7,
        symbol: "divide",
        tile2: 7,
        remainingTiles: [1, 16, 1],
      },
      {
        tile1: 16,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [1, 16],
      },
      { tile1: 16, symbol: "divide", tile2: 1, remainingTiles: [16] },
    ],
  },
  "3-3-4-4-7-7": {
    bigNumber: 7,
    tiles: [4, 3, 3, 7, 4],
    symbols: { add: 2, subtract: 0, multiply: 0, divide: 2 },
    solution: [
      {
        tile1: 4,
        symbol: "add",
        tile2: 3,
        remainingTiles: [4, 7, 3, 7],
      },
      { tile1: 3, symbol: "add", tile2: 4, remainingTiles: [7, 7, 7] },
      { tile1: 7, symbol: "divide", tile2: 7, remainingTiles: [7, 1] },
      { tile1: 7, symbol: "divide", tile2: 1, remainingTiles: [7] },
    ],
  },
  "1-1-4-6-7-48": {
    bigNumber: 48,
    tiles: [4, 7, 6, 1, 1],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 6,
        remainingTiles: [4, 1, 1, 42],
      },
      {
        tile1: 42,
        symbol: "add",
        tile2: 1,
        remainingTiles: [4, 1, 43],
      },
      { tile1: 1, symbol: "add", tile2: 43, remainingTiles: [4, 44] },
      { tile1: 44, symbol: "add", tile2: 4, remainingTiles: [48] },
    ],
  },
  "1-7-7-8-9-67": {
    bigNumber: 67,
    tiles: [9, 8, 7, 1, 7],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 7,
        remainingTiles: [1, 8, 9, 49],
      },
      {
        tile1: 49,
        symbol: "add",
        tile2: 1,
        remainingTiles: [8, 9, 50],
      },
      { tile1: 8, symbol: "add", tile2: 9, remainingTiles: [50, 17] },
      { tile1: 50, symbol: "add", tile2: 17, remainingTiles: [67] },
    ],
  },
  "1-3-5-6-7-30": {
    bigNumber: 30,
    tiles: [6, 7, 3, 1, 5],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 6,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [5, 7, 3, 6],
      },
      {
        tile1: 6,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [5, 7, 18],
      },
      { tile1: 7, symbol: "add", tile2: 5, remainingTiles: [18, 12] },
      { tile1: 18, symbol: "add", tile2: 12, remainingTiles: [30] },
    ],
  },
  "1-3-4-7-9-62": {
    bigNumber: 62,
    tiles: [4, 9, 7, 1, 3],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 7,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [9, 3, 4, 7],
      },
      {
        tile1: 9,
        symbol: "multiply",
        tile2: 7,
        remainingTiles: [3, 4, 63],
      },
      {
        tile1: 63,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [3, 59],
      },
      { tile1: 3, symbol: "add", tile2: 59, remainingTiles: [62] },
    ],
  },
  "1-2-4-6-9-28": {
    bigNumber: 28,
    tiles: [4, 6, 9, 1, 2],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 6,
        symbol: "add",
        tile2: 4,
        remainingTiles: [9, 1, 2, 10],
      },
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 2,
        remainingTiles: [9, 10, 2],
      },
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [10, 18],
      },
      { tile1: 18, symbol: "add", tile2: 10, remainingTiles: [28] },
    ],
  },
  "2-4-7-7-8-37": {
    bigNumber: 37,
    tiles: [4, 2, 7, 7, 8],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 7,
        symbol: "add",
        tile2: 2,
        remainingTiles: [8, 4, 7, 9],
      },
      {
        tile1: 8,
        symbol: "subtract",
        tile2: 7,
        remainingTiles: [4, 9, 1],
      },
      {
        tile1: 4,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [1, 36],
      },
      { tile1: 36, symbol: "add", tile2: 1, remainingTiles: [37] },
    ],
  },
  "1-3-3-5-7-30": {
    bigNumber: 30,
    tiles: [3, 3, 7, 1, 5],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 5,
        symbol: "add",
        tile2: 3,
        remainingTiles: [7, 1, 3, 8],
      },
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [1, 8, 21],
      },
      { tile1: 21, symbol: "add", tile2: 1, remainingTiles: [8, 22] },
      { tile1: 8, symbol: "add", tile2: 22, remainingTiles: [30] },
    ],
  },
  "2-5-5-7-9-25": {
    bigNumber: 25,
    tiles: [2, 5, 7, 9, 5],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 5,
        symbol: "divide",
        tile2: 5,
        remainingTiles: [2, 9, 7, 1],
      },
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [2, 7, 9],
      },
      {
        tile1: 9,
        symbol: "multiply",
        tile2: 2,
        remainingTiles: [7, 18],
      },
      { tile1: 7, symbol: "add", tile2: 18, remainingTiles: [25] },
    ],
  },
  "3-3-5-5-5-44": {
    bigNumber: 44,
    tiles: [5, 5, 3, 5, 3],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 5,
        symbol: "add",
        tile2: 3,
        remainingTiles: [3, 5, 5, 8],
      },
      { tile1: 8, symbol: "add", tile2: 5, remainingTiles: [3, 5, 13] },
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 13,
        remainingTiles: [5, 39],
      },
      { tile1: 5, symbol: "add", tile2: 39, remainingTiles: [44] },
    ],
  },
  "3-3-4-8-9-4": {
    bigNumber: 4,
    tiles: [3, 3, 9, 8, 4],
    symbols: { add: 0, subtract: 1, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 9,
        symbol: "subtract",
        tile2: 8,
        remainingTiles: [3, 4, 3, 1],
      },
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [3, 1, 12],
      },
      {
        tile1: 12,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [3, 12],
      },
      { tile1: 12, symbol: "divide", tile2: 3, remainingTiles: [4] },
    ],
  },
  "1-4-6-6-7-44": {
    bigNumber: 44,
    tiles: [6, 4, 1, 7, 6],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 6,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [6, 1, 7, 2],
      },
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 6,
        remainingTiles: [7, 2, 6],
      },
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 6,
        remainingTiles: [2, 42],
      },
      { tile1: 42, symbol: "add", tile2: 2, remainingTiles: [44] },
    ],
  },
  "1-2-2-8-8-68": {
    bigNumber: 68,
    tiles: [1, 8, 2, 8, 2],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 8,
        remainingTiles: [2, 2, 8, 8],
      },
      { tile1: 2, symbol: "add", tile2: 2, remainingTiles: [8, 8, 4] },
      {
        tile1: 8,
        symbol: "multiply",
        tile2: 8,
        remainingTiles: [4, 64],
      },
      { tile1: 4, symbol: "add", tile2: 64, remainingTiles: [68] },
    ],
  },
  "2-3-3-7-8-12": {
    bigNumber: 12,
    tiles: [3, 7, 3, 8, 2],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [3, 8, 2, 21],
      },
      {
        tile1: 8,
        symbol: "subtract",
        tile2: 2,
        remainingTiles: [3, 21, 6],
      },
      { tile1: 6, symbol: "add", tile2: 3, remainingTiles: [21, 9] },
      { tile1: 21, symbol: "subtract", tile2: 9, remainingTiles: [12] },
    ],
  },
  "2-3-4-6-7-14": {
    bigNumber: 14,
    tiles: [2, 4, 6, 3, 7],
    symbols: { add: 3, subtract: 1, multiply: 0, divide: 0 },
    solution: [
      {
        tile1: 6,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [7, 2, 3, 2],
      },
      { tile1: 3, symbol: "add", tile2: 2, remainingTiles: [7, 2, 5] },
      { tile1: 7, symbol: "add", tile2: 2, remainingTiles: [5, 9] },
      { tile1: 5, symbol: "add", tile2: 9, remainingTiles: [14] },
    ],
  },
  "1-3-6-7-8-46": {
    bigNumber: 46,
    tiles: [6, 8, 1, 7, 3],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 6,
        symbol: "multiply",
        tile2: 7,
        remainingTiles: [1, 3, 8, 42],
      },
      { tile1: 1, symbol: "add", tile2: 3, remainingTiles: [8, 42, 4] },
      { tile1: 8, symbol: "add", tile2: 42, remainingTiles: [4, 50] },
      { tile1: 50, symbol: "subtract", tile2: 4, remainingTiles: [46] },
    ],
  },
  "1-5-6-9-9-11": {
    bigNumber: 11,
    tiles: [9, 1, 5, 9, 6],
    symbols: { add: 1, subtract: 0, multiply: 0, divide: 3 },
    solution: [
      {
        tile1: 9,
        symbol: "divide",
        tile2: 9,
        remainingTiles: [5, 6, 1, 1],
      },
      {
        tile1: 6,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [5, 1, 6],
      },
      { tile1: 6, symbol: "divide", tile2: 1, remainingTiles: [5, 6] },
      { tile1: 6, symbol: "add", tile2: 5, remainingTiles: [11] },
    ],
  },
  "2-4-4-6-8-6": {
    bigNumber: 6,
    tiles: [4, 4, 2, 8, 6],
    symbols: { add: 0, subtract: 2, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 4,
        symbol: "divide",
        tile2: 4,
        remainingTiles: [8, 2, 6, 1],
      },
      {
        tile1: 6,
        symbol: "subtract",
        tile2: 1,
        remainingTiles: [8, 2, 5],
      },
      {
        tile1: 8,
        symbol: "subtract",
        tile2: 5,
        remainingTiles: [2, 3],
      },
      { tile1: 2, symbol: "multiply", tile2: 3, remainingTiles: [6] },
    ],
  },
  "2-7-7-9-9-16": {
    bigNumber: 16,
    tiles: [9, 7, 7, 2, 9],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 9,
        symbol: "subtract",
        tile2: 7,
        remainingTiles: [9, 2, 7, 2],
      },
      {
        tile1: 2,
        symbol: "divide",
        tile2: 2,
        remainingTiles: [9, 7, 1],
      },
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 7,
        remainingTiles: [9, 7],
      },
      { tile1: 9, symbol: "add", tile2: 7, remainingTiles: [16] },
    ],
  },
  "2-2-6-8-9-34": {
    bigNumber: 34,
    tiles: [2, 8, 9, 2, 6],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 2,
        remainingTiles: [9, 8, 6, 4],
      },
      {
        tile1: 9,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [8, 6, 36],
      },
      {
        tile1: 36,
        symbol: "subtract",
        tile2: 8,
        remainingTiles: [6, 28],
      },
      { tile1: 28, symbol: "add", tile2: 6, remainingTiles: [34] },
    ],
  },
  "1-2-4-6-8-64": {
    bigNumber: 64,
    tiles: [4, 6, 2, 8, 1],
    symbols: { add: 0, subtract: 1, multiply: 3, divide: 0 },
    solution: [
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 6,
        remainingTiles: [1, 4, 8, 12],
      },
      {
        tile1: 4,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [8, 12, 4],
      },
      {
        tile1: 12,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [8, 8],
      },
      { tile1: 8, symbol: "multiply", tile2: 8, remainingTiles: [64] },
    ],
  },
  "2-4-6-7-8-63": {
    bigNumber: 63,
    tiles: [6, 4, 2, 7, 8],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [6, 7, 8, 8],
      },
      { tile1: 7, symbol: "add", tile2: 8, remainingTiles: [6, 8, 15] },
      {
        tile1: 6,
        symbol: "multiply",
        tile2: 8,
        remainingTiles: [15, 48],
      },
      { tile1: 15, symbol: "add", tile2: 48, remainingTiles: [63] },
    ],
  },
  "1-4-8-9-9-2": {
    bigNumber: 2,
    tiles: [1, 9, 4, 9, 8],
    symbols: { add: 0, subtract: 0, multiply: 1, divide: 3 },
    solution: [
      {
        tile1: 9,
        symbol: "divide",
        tile2: 9,
        remainingTiles: [8, 4, 1, 1],
      },
      {
        tile1: 1,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [8, 4, 1],
      },
      { tile1: 8, symbol: "divide", tile2: 4, remainingTiles: [1, 2] },
      { tile1: 2, symbol: "multiply", tile2: 1, remainingTiles: [2] },
    ],
  },
  "5-7-7-9-9-28": {
    bigNumber: 28,
    tiles: [5, 9, 7, 7, 9],
    symbols: { add: 0, subtract: 1, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 9,
        symbol: "multiply",
        tile2: 5,
        remainingTiles: [9, 7, 7, 45],
      },
      {
        tile1: 45,
        symbol: "divide",
        tile2: 9,
        remainingTiles: [7, 7, 5],
      },
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 7,
        remainingTiles: [7, 35],
      },
      { tile1: 35, symbol: "subtract", tile2: 7, remainingTiles: [28] },
    ],
  },
  "2-5-5-7-9-1": {
    bigNumber: 1,
    tiles: [2, 7, 5, 9, 5],
    symbols: { add: 2, subtract: 1, multiply: 0, divide: 1 },
    solution: [
      {
        tile1: 5,
        symbol: "add",
        tile2: 9,
        remainingTiles: [7, 5, 2, 14],
      },
      { tile1: 7, symbol: "add", tile2: 2, remainingTiles: [5, 14, 9] },
      {
        tile1: 14,
        symbol: "subtract",
        tile2: 9,
        remainingTiles: [5, 5],
      },
      { tile1: 5, symbol: "divide", tile2: 5, remainingTiles: [1] },
    ],
  },
  "3-4-4-5-9-4": {
    bigNumber: 4,
    tiles: [4, 3, 5, 4, 9],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 4,
        symbol: "add",
        tile2: 4,
        remainingTiles: [3, 5, 9, 8],
      },
      {
        tile1: 9,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [5, 8, 27],
      },
      { tile1: 5, symbol: "add", tile2: 27, remainingTiles: [8, 32] },
      { tile1: 32, symbol: "divide", tile2: 8, remainingTiles: [4] },
    ],
  },
  "4-5-7-8-8-28": {
    bigNumber: 28,
    tiles: [7, 5, 4, 8, 8],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 8,
        symbol: "multiply",
        tile2: 8,
        remainingTiles: [4, 7, 5, 64],
      },
      {
        tile1: 64,
        symbol: "divide",
        tile2: 4,
        remainingTiles: [7, 5, 16],
      },
      { tile1: 7, symbol: "add", tile2: 16, remainingTiles: [5, 23] },
      { tile1: 23, symbol: "add", tile2: 5, remainingTiles: [28] },
    ],
  },
  "2-2-4-6-9-54": {
    bigNumber: 54,
    tiles: [9, 2, 2, 4, 6],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 2,
        symbol: "add",
        tile2: 2,
        remainingTiles: [6, 9, 4, 4],
      },
      {
        tile1: 4,
        symbol: "divide",
        tile2: 4,
        remainingTiles: [6, 9, 1],
      },
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [6, 9],
      },
      { tile1: 9, symbol: "multiply", tile2: 6, remainingTiles: [54] },
    ],
  },
  "2-3-4-4-5-65": {
    bigNumber: 65,
    tiles: [3, 4, 5, 2, 4],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 4,
        symbol: "add",
        tile2: 2,
        remainingTiles: [5, 3, 4, 6],
      },
      { tile1: 3, symbol: "add", tile2: 6, remainingTiles: [5, 4, 9] },
      { tile1: 9, symbol: "add", tile2: 4, remainingTiles: [5, 13] },
      { tile1: 5, symbol: "multiply", tile2: 13, remainingTiles: [65] },
    ],
  },
  "2-6-8-9-9-69": {
    bigNumber: 69,
    tiles: [9, 6, 8, 2, 9],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 8,
        symbol: "divide",
        tile2: 2,
        remainingTiles: [6, 9, 9, 4],
      },
      { tile1: 9, symbol: "add", tile2: 6, remainingTiles: [9, 4, 15] },
      {
        tile1: 15,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [9, 60],
      },
      { tile1: 60, symbol: "add", tile2: 9, remainingTiles: [69] },
    ],
  },
  "1-2-4-5-8-83": {
    bigNumber: 83,
    tiles: [4, 8, 1, 2, 5],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 4,
        symbol: "subtract",
        tile2: 1,
        remainingTiles: [5, 8, 2, 3],
      },
      {
        tile1: 8,
        symbol: "multiply",
        tile2: 5,
        remainingTiles: [2, 3, 40],
      },
      {
        tile1: 40,
        symbol: "multiply",
        tile2: 2,
        remainingTiles: [3, 80],
      },
      { tile1: 3, symbol: "add", tile2: 80, remainingTiles: [83] },
    ],
  },
  "4-5-5-6-9-79": {
    bigNumber: 79,
    tiles: [4, 9, 5, 6, 5],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 9,
        symbol: "multiply",
        tile2: 6,
        remainingTiles: [5, 5, 4, 54],
      },
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [5, 54, 20],
      },
      { tile1: 20, symbol: "add", tile2: 5, remainingTiles: [54, 25] },
      { tile1: 25, symbol: "add", tile2: 54, remainingTiles: [79] },
    ],
  },
  "2-3-4-5-6-56": {
    bigNumber: 56,
    tiles: [6, 4, 3, 5, 2],
    symbols: { add: 1, subtract: 0, multiply: 3, divide: 0 },
    solution: [
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 2,
        remainingTiles: [4, 6, 5, 6],
      },
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [6, 6, 20],
      },
      {
        tile1: 6,
        symbol: "multiply",
        tile2: 6,
        remainingTiles: [20, 36],
      },
      { tile1: 20, symbol: "add", tile2: 36, remainingTiles: [56] },
    ],
  },
  "1-2-3-8-8-66": {
    bigNumber: 66,
    tiles: [8, 8, 3, 2, 1],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 8,
        symbol: "subtract",
        tile2: 2,
        remainingTiles: [8, 3, 1, 6],
      },
      { tile1: 3, symbol: "add", tile2: 8, remainingTiles: [1, 6, 11] },
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 11,
        remainingTiles: [6, 11],
      },
      { tile1: 11, symbol: "multiply", tile2: 6, remainingTiles: [66] },
    ],
  },
  "4-5-5-5-8-7": {
    bigNumber: 7,
    tiles: [5, 4, 8, 5, 5],
    symbols: { add: 3, subtract: 1, multiply: 0, divide: 0 },
    solution: [
      {
        tile1: 5,
        symbol: "add",
        tile2: 5,
        remainingTiles: [5, 8, 4, 10],
      },
      {
        tile1: 4,
        symbol: "add",
        tile2: 8,
        remainingTiles: [5, 10, 12],
      },
      { tile1: 12, symbol: "add", tile2: 5, remainingTiles: [10, 17] },
      { tile1: 17, symbol: "subtract", tile2: 10, remainingTiles: [7] },
    ],
  },
  "1-1-4-4-8-10": {
    bigNumber: 10,
    tiles: [1, 4, 1, 4, 8],
    symbols: { add: 2, subtract: 0, multiply: 0, divide: 2 },
    solution: [
      {
        tile1: 4,
        symbol: "divide",
        tile2: 4,
        remainingTiles: [8, 1, 1, 1],
      },
      {
        tile1: 8,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [1, 1, 8],
      },
      { tile1: 1, symbol: "add", tile2: 1, remainingTiles: [8, 2] },
      { tile1: 8, symbol: "add", tile2: 2, remainingTiles: [10] },
    ],
  },
  "3-5-6-8-9-58": {
    bigNumber: 58,
    tiles: [5, 9, 3, 6, 8],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 8,
        remainingTiles: [9, 3, 6, 40],
      },
      {
        tile1: 9,
        symbol: "divide",
        tile2: 3,
        remainingTiles: [6, 40, 3],
      },
      {
        tile1: 6,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [40, 18],
      },
      { tile1: 40, symbol: "add", tile2: 18, remainingTiles: [58] },
    ],
  },
  "1-3-4-6-9-25": {
    bigNumber: 25,
    tiles: [1, 6, 4, 3, 9],
    symbols: { add: 0, subtract: 2, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 4,
        symbol: "subtract",
        tile2: 1,
        remainingTiles: [9, 3, 6, 3],
      },
      {
        tile1: 6,
        symbol: "divide",
        tile2: 3,
        remainingTiles: [9, 3, 2],
      },
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [2, 27],
      },
      { tile1: 27, symbol: "subtract", tile2: 2, remainingTiles: [25] },
    ],
  },
  "1-1-1-3-4-13": {
    bigNumber: 13,
    tiles: [4, 1, 3, 1, 1],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [3, 1, 1, 4],
      },
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [1, 1, 12],
      },
      {
        tile1: 12,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [1, 12],
      },
      { tile1: 1, symbol: "add", tile2: 12, remainingTiles: [13] },
    ],
  },
  "1-3-5-5-6-11": {
    bigNumber: 11,
    tiles: [6, 5, 5, 1, 3],
    symbols: { add: 3, subtract: 0, multiply: 0, divide: 1 },
    solution: [
      {
        tile1: 5,
        symbol: "divide",
        tile2: 5,
        remainingTiles: [1, 6, 3, 1],
      },
      { tile1: 3, symbol: "add", tile2: 1, remainingTiles: [1, 6, 4] },
      { tile1: 6, symbol: "add", tile2: 4, remainingTiles: [1, 10] },
      { tile1: 10, symbol: "add", tile2: 1, remainingTiles: [11] },
    ],
  },
  "2-5-6-7-9-38": {
    bigNumber: 38,
    tiles: [7, 2, 6, 5, 9],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 5,
        symbol: "add",
        tile2: 6,
        remainingTiles: [7, 2, 9, 11],
      },
      {
        tile1: 7,
        symbol: "add",
        tile2: 9,
        remainingTiles: [2, 11, 16],
      },
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 11,
        remainingTiles: [16, 22],
      },
      { tile1: 16, symbol: "add", tile2: 22, remainingTiles: [38] },
    ],
  },
  "1-3-5-5-5-2": {
    bigNumber: 2,
    tiles: [5, 3, 5, 5, 1],
    symbols: { add: 0, subtract: 1, multiply: 1, divide: 2 },
    solution: [
      {
        tile1: 5,
        symbol: "subtract",
        tile2: 3,
        remainingTiles: [5, 5, 1, 2],
      },
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 2,
        remainingTiles: [5, 1, 10],
      },
      { tile1: 10, symbol: "divide", tile2: 5, remainingTiles: [1, 2] },
      { tile1: 2, symbol: "divide", tile2: 1, remainingTiles: [2] },
    ],
  },
  "1-2-5-6-9-84": {
    bigNumber: 84,
    tiles: [2, 6, 1, 9, 5],
    symbols: { add: 0, subtract: 1, multiply: 3, divide: 0 },
    solution: [
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [6, 1, 5, 18],
      },
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 18,
        remainingTiles: [6, 1, 90],
      },
      {
        tile1: 6,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [90, 6],
      },
      { tile1: 90, symbol: "subtract", tile2: 6, remainingTiles: [84] },
    ],
  },
  "3-3-4-6-6-30": {
    bigNumber: 30,
    tiles: [3, 4, 6, 3, 6],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [4, 6, 6, 9],
      },
      { tile1: 6, symbol: "add", tile2: 9, remainingTiles: [4, 6, 15] },
      {
        tile1: 6,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [15, 2],
      },
      { tile1: 15, symbol: "multiply", tile2: 2, remainingTiles: [30] },
    ],
  },
  "1-3-4-8-8-12": {
    bigNumber: 12,
    tiles: [3, 8, 1, 8, 4],
    symbols: { add: 0, subtract: 0, multiply: 3, divide: 1 },
    solution: [
      {
        tile1: 8,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [8, 3, 4, 8],
      },
      {
        tile1: 8,
        symbol: "divide",
        tile2: 8,
        remainingTiles: [3, 4, 1],
      },
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [4, 3],
      },
      { tile1: 3, symbol: "multiply", tile2: 4, remainingTiles: [12] },
    ],
  },
  "1-4-6-7-8-75": {
    bigNumber: 75,
    tiles: [8, 6, 1, 4, 7],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 4,
        symbol: "add",
        tile2: 7,
        remainingTiles: [1, 6, 8, 11],
      },
      {
        tile1: 6,
        symbol: "multiply",
        tile2: 11,
        remainingTiles: [1, 8, 66],
      },
      { tile1: 8, symbol: "add", tile2: 66, remainingTiles: [1, 74] },
      { tile1: 1, symbol: "add", tile2: 74, remainingTiles: [75] },
    ],
  },
  "1-3-5-6-8-82": {
    bigNumber: 82,
    tiles: [3, 5, 1, 8, 6],
    symbols: { add: 0, subtract: 1, multiply: 3, divide: 0 },
    solution: [
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 6,
        remainingTiles: [1, 5, 8, 18],
      },
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 18,
        remainingTiles: [1, 8, 90],
      },
      {
        tile1: 90,
        symbol: "subtract",
        tile2: 8,
        remainingTiles: [1, 82],
      },
      { tile1: 82, symbol: "multiply", tile2: 1, remainingTiles: [82] },
    ],
  },
  "1-4-4-4-8-4": {
    bigNumber: 4,
    tiles: [4, 8, 1, 4, 4],
    symbols: { add: 0, subtract: 1, multiply: 1, divide: 2 },
    solution: [
      {
        tile1: 8,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [4, 4, 4, 8],
      },
      {
        tile1: 4,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [4, 8, 16],
      },
      { tile1: 16, symbol: "divide", tile2: 4, remainingTiles: [8, 4] },
      { tile1: 8, symbol: "subtract", tile2: 4, remainingTiles: [4] },
    ],
  },
  "1-2-4-5-7-18": {
    bigNumber: 18,
    tiles: [2, 1, 5, 4, 7],
    symbols: { add: 1, subtract: 0, multiply: 1, divide: 2 },
    solution: [
      {
        tile1: 4,
        symbol: "divide",
        tile2: 2,
        remainingTiles: [7, 5, 1, 2],
      },
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 7,
        remainingTiles: [1, 2, 35],
      },
      { tile1: 35, symbol: "add", tile2: 1, remainingTiles: [2, 36] },
      { tile1: 36, symbol: "divide", tile2: 2, remainingTiles: [18] },
    ],
  },
  "2-2-6-9-9-31": {
    bigNumber: 31,
    tiles: [2, 9, 9, 6, 2],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 9,
        symbol: "subtract",
        tile2: 6,
        remainingTiles: [2, 2, 9, 3],
      },
      {
        tile1: 9,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [2, 2, 27],
      },
      { tile1: 27, symbol: "add", tile2: 2, remainingTiles: [2, 29] },
      { tile1: 2, symbol: "add", tile2: 29, remainingTiles: [31] },
    ],
  },
  "1-4-5-6-9-13": {
    bigNumber: 13,
    tiles: [6, 9, 1, 4, 5],
    symbols: { add: 3, subtract: 1, multiply: 0, divide: 0 },
    solution: [
      {
        tile1: 1,
        symbol: "add",
        tile2: 5,
        remainingTiles: [9, 6, 4, 6],
      },
      { tile1: 9, symbol: "add", tile2: 6, remainingTiles: [6, 4, 15] },
      { tile1: 4, symbol: "add", tile2: 15, remainingTiles: [6, 19] },
      { tile1: 19, symbol: "subtract", tile2: 6, remainingTiles: [13] },
    ],
  },
  "5-5-7-7-8-94": {
    bigNumber: 94,
    tiles: [7, 8, 5, 7, 5],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 5,
        symbol: "add",
        tile2: 7,
        remainingTiles: [7, 8, 5, 12],
      },
      {
        tile1: 8,
        symbol: "multiply",
        tile2: 12,
        remainingTiles: [7, 5, 96],
      },
      {
        tile1: 96,
        symbol: "subtract",
        tile2: 7,
        remainingTiles: [5, 89],
      },
      { tile1: 89, symbol: "add", tile2: 5, remainingTiles: [94] },
    ],
  },
  "1-3-3-6-7-30": {
    bigNumber: 30,
    tiles: [6, 7, 3, 1, 3],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 7,
        remainingTiles: [3, 1, 6, 21],
      },
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [6, 21, 3],
      },
      { tile1: 3, symbol: "add", tile2: 6, remainingTiles: [21, 9] },
      { tile1: 21, symbol: "add", tile2: 9, remainingTiles: [30] },
    ],
  },
  "3-4-5-6-7-61": {
    bigNumber: 61,
    tiles: [6, 3, 5, 4, 7],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 5,
        remainingTiles: [6, 7, 4, 15],
      },
      {
        tile1: 7,
        symbol: "subtract",
        tile2: 6,
        remainingTiles: [4, 15, 1],
      },
      {
        tile1: 15,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [1, 60],
      },
      { tile1: 1, symbol: "add", tile2: 60, remainingTiles: [61] },
    ],
  },
  "1-3-3-4-7-17": {
    bigNumber: 17,
    tiles: [3, 3, 1, 7, 4],
    symbols: { add: 3, subtract: 0, multiply: 0, divide: 1 },
    solution: [
      {
        tile1: 3,
        symbol: "add",
        tile2: 4,
        remainingTiles: [1, 3, 7, 7],
      },
      {
        tile1: 7,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [3, 7, 7],
      },
      { tile1: 7, symbol: "add", tile2: 7, remainingTiles: [3, 14] },
      { tile1: 14, symbol: "add", tile2: 3, remainingTiles: [17] },
    ],
  },
  "1-7-7-9-9-13": {
    bigNumber: 13,
    tiles: [9, 7, 7, 9, 1],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 9,
        symbol: "divide",
        tile2: 9,
        remainingTiles: [7, 7, 1, 1],
      },
      {
        tile1: 7,
        symbol: "subtract",
        tile2: 1,
        remainingTiles: [7, 1, 6],
      },
      {
        tile1: 6,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [7, 6],
      },
      { tile1: 7, symbol: "add", tile2: 6, remainingTiles: [13] },
    ],
  },
  "2-2-4-5-9-14": {
    bigNumber: 14,
    tiles: [5, 2, 2, 9, 4],
    symbols: { add: 1, subtract: 0, multiply: 0, divide: 3 },
    solution: [
      {
        tile1: 9,
        symbol: "add",
        tile2: 5,
        remainingTiles: [2, 2, 4, 14],
      },
      {
        tile1: 4,
        symbol: "divide",
        tile2: 2,
        remainingTiles: [2, 14, 2],
      },
      { tile1: 2, symbol: "divide", tile2: 2, remainingTiles: [14, 1] },
      { tile1: 14, symbol: "divide", tile2: 1, remainingTiles: [14] },
    ],
  },
  "3-6-7-9-9-19": {
    bigNumber: 19,
    tiles: [9, 3, 6, 9, 7],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 9,
        symbol: "subtract",
        tile2: 7,
        remainingTiles: [6, 9, 3, 2],
      },
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [6, 2, 27],
      },
      { tile1: 6, symbol: "add", tile2: 2, remainingTiles: [27, 8] },
      { tile1: 27, symbol: "subtract", tile2: 8, remainingTiles: [19] },
    ],
  },
  "5-5-6-7-8-5": {
    bigNumber: 5,
    tiles: [8, 6, 5, 7, 5],
    symbols: { add: 1, subtract: 3, multiply: 0, divide: 0 },
    solution: [
      {
        tile1: 8,
        symbol: "add",
        tile2: 5,
        remainingTiles: [6, 7, 5, 13],
      },
      {
        tile1: 7,
        symbol: "subtract",
        tile2: 5,
        remainingTiles: [6, 13, 2],
      },
      {
        tile1: 13,
        symbol: "subtract",
        tile2: 2,
        remainingTiles: [6, 11],
      },
      { tile1: 11, symbol: "subtract", tile2: 6, remainingTiles: [5] },
    ],
  },
  "1-1-2-4-9-44": {
    bigNumber: 44,
    tiles: [4, 1, 2, 9, 1],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 9,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [2, 4, 1, 9],
      },
      {
        tile1: 4,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [2, 9, 4],
      },
      { tile1: 9, symbol: "add", tile2: 2, remainingTiles: [4, 11] },
      { tile1: 11, symbol: "multiply", tile2: 4, remainingTiles: [44] },
    ],
  },
  "2-2-5-7-9-22": {
    bigNumber: 22,
    tiles: [2, 7, 5, 9, 2],
    symbols: { add: 3, subtract: 0, multiply: 0, divide: 1 },
    solution: [
      {
        tile1: 2,
        symbol: "divide",
        tile2: 2,
        remainingTiles: [9, 5, 7, 1],
      },
      { tile1: 5, symbol: "add", tile2: 1, remainingTiles: [9, 7, 6] },
      { tile1: 9, symbol: "add", tile2: 6, remainingTiles: [7, 15] },
      { tile1: 7, symbol: "add", tile2: 15, remainingTiles: [22] },
    ],
  },
  "3-4-4-7-7-47": {
    bigNumber: 47,
    tiles: [4, 4, 7, 3, 7],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 4,
        symbol: "multiply",
        tile2: 7,
        remainingTiles: [4, 7, 3, 28],
      },
      {
        tile1: 4,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [7, 28, 12],
      },
      { tile1: 12, symbol: "add", tile2: 7, remainingTiles: [28, 19] },
      { tile1: 19, symbol: "add", tile2: 28, remainingTiles: [47] },
    ],
  },
  "3-3-4-5-7-6": {
    bigNumber: 6,
    tiles: [3, 4, 5, 7, 3],
    symbols: { add: 2, subtract: 2, multiply: 0, divide: 0 },
    solution: [
      {
        tile1: 7,
        symbol: "add",
        tile2: 3,
        remainingTiles: [5, 3, 4, 10],
      },
      {
        tile1: 5,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [3, 10, 1],
      },
      { tile1: 1, symbol: "add", tile2: 3, remainingTiles: [10, 4] },
      { tile1: 10, symbol: "subtract", tile2: 4, remainingTiles: [6] },
    ],
  },
  "1-4-5-8-9-1": {
    bigNumber: 1,
    tiles: [5, 9, 4, 1, 8],
    symbols: { add: 2, subtract: 0, multiply: 0, divide: 2 },
    solution: [
      {
        tile1: 5,
        symbol: "add",
        tile2: 8,
        remainingTiles: [9, 4, 1, 13],
      },
      {
        tile1: 9,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [4, 13, 9],
      },
      { tile1: 4, symbol: "add", tile2: 9, remainingTiles: [13, 13] },
      { tile1: 13, symbol: "divide", tile2: 13, remainingTiles: [1] },
    ],
  },
  "1-2-2-5-6-6": {
    bigNumber: 6,
    tiles: [2, 2, 6, 5, 1],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 2,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [5, 6, 2, 2],
      },
      {
        tile1: 6,
        symbol: "subtract",
        tile2: 5,
        remainingTiles: [2, 2, 1],
      },
      { tile1: 2, symbol: "add", tile2: 1, remainingTiles: [2, 3] },
      { tile1: 2, symbol: "multiply", tile2: 3, remainingTiles: [6] },
    ],
  },
  "1-2-3-6-7-41": {
    bigNumber: 41,
    tiles: [1, 7, 3, 2, 6],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 3,
        remainingTiles: [7, 6, 1, 6],
      },
      {
        tile1: 6,
        symbol: "subtract",
        tile2: 1,
        remainingTiles: [7, 6, 5],
      },
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 5,
        remainingTiles: [6, 35],
      },
      { tile1: 6, symbol: "add", tile2: 35, remainingTiles: [41] },
    ],
  },
  "3-5-7-8-9-7": {
    bigNumber: 7,
    tiles: [5, 7, 8, 3, 9],
    symbols: { add: 1, subtract: 2, multiply: 0, divide: 1 },
    solution: [
      {
        tile1: 9,
        symbol: "divide",
        tile2: 3,
        remainingTiles: [5, 7, 8, 3],
      },
      {
        tile1: 8,
        symbol: "subtract",
        tile2: 5,
        remainingTiles: [7, 3, 3],
      },
      {
        tile1: 7,
        symbol: "subtract",
        tile2: 3,
        remainingTiles: [3, 4],
      },
      { tile1: 3, symbol: "add", tile2: 4, remainingTiles: [7] },
    ],
  },
  "1-3-4-6-9-45": {
    bigNumber: 45,
    tiles: [1, 9, 4, 6, 3],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 6,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [1, 3, 9, 2],
      },
      { tile1: 2, symbol: "add", tile2: 3, remainingTiles: [1, 9, 5] },
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [9, 5],
      },
      { tile1: 5, symbol: "multiply", tile2: 9, remainingTiles: [45] },
    ],
  },
  "3-4-5-7-9-45": {
    bigNumber: 45,
    tiles: [5, 4, 3, 9, 7],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [5, 4, 3, 63],
      },
      { tile1: 4, symbol: "add", tile2: 3, remainingTiles: [5, 63, 7] },
      { tile1: 63, symbol: "divide", tile2: 7, remainingTiles: [5, 9] },
      { tile1: 5, symbol: "multiply", tile2: 9, remainingTiles: [45] },
    ],
  },
  "1-3-3-4-7-3": {
    bigNumber: 3,
    tiles: [4, 3, 1, 3, 7],
    symbols: { add: 1, subtract: 0, multiply: 1, divide: 2 },
    solution: [
      {
        tile1: 4,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [3, 3, 7, 4],
      },
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 7,
        remainingTiles: [3, 4, 21],
      },
      { tile1: 4, symbol: "add", tile2: 3, remainingTiles: [21, 7] },
      { tile1: 21, symbol: "divide", tile2: 7, remainingTiles: [3] },
    ],
  },
  "4-4-5-6-7-33": {
    bigNumber: 33,
    tiles: [4, 4, 6, 7, 5],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 7,
        remainingTiles: [6, 4, 4, 35],
      },
      {
        tile1: 35,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [6, 4, 31],
      },
      {
        tile1: 6,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [31, 2],
      },
      { tile1: 2, symbol: "add", tile2: 31, remainingTiles: [33] },
    ],
  },
  "3-3-3-4-6-3": {
    bigNumber: 3,
    tiles: [6, 3, 3, 3, 4],
    symbols: { add: 1, subtract: 0, multiply: 1, divide: 2 },
    solution: [
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [6, 3, 3, 12],
      },
      { tile1: 3, symbol: "add", tile2: 3, remainingTiles: [6, 12, 6] },
      { tile1: 12, symbol: "divide", tile2: 6, remainingTiles: [6, 2] },
      { tile1: 6, symbol: "divide", tile2: 2, remainingTiles: [3] },
    ],
  },
  "2-3-6-6-7-8": {
    bigNumber: 8,
    tiles: [6, 6, 2, 7, 3],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 3,
        symbol: "multiply",
        tile2: 6,
        remainingTiles: [7, 2, 6, 18],
      },
      {
        tile1: 18,
        symbol: "divide",
        tile2: 6,
        remainingTiles: [7, 2, 3],
      },
      {
        tile1: 3,
        symbol: "subtract",
        tile2: 2,
        remainingTiles: [7, 1],
      },
      { tile1: 7, symbol: "add", tile2: 1, remainingTiles: [8] },
    ],
  },
  "1-2-3-4-8-7": {
    bigNumber: 7,
    tiles: [4, 1, 8, 3, 2],
    symbols: { add: 1, subtract: 2, multiply: 0, divide: 1 },
    solution: [
      {
        tile1: 2,
        symbol: "subtract",
        tile2: 1,
        remainingTiles: [8, 3, 4, 1],
      },
      { tile1: 3, symbol: "add", tile2: 8, remainingTiles: [4, 1, 11] },
      { tile1: 4, symbol: "divide", tile2: 1, remainingTiles: [11, 4] },
      { tile1: 11, symbol: "subtract", tile2: 4, remainingTiles: [7] },
    ],
  },
  "2-6-6-7-7-87": {
    bigNumber: 87,
    tiles: [6, 7, 6, 7, 2],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 7,
        symbol: "add",
        tile2: 6,
        remainingTiles: [7, 6, 2, 13],
      },
      {
        tile1: 6,
        symbol: "multiply",
        tile2: 13,
        remainingTiles: [7, 2, 78],
      },
      { tile1: 78, symbol: "add", tile2: 7, remainingTiles: [2, 85] },
      { tile1: 2, symbol: "add", tile2: 85, remainingTiles: [87] },
    ],
  },
  "5-6-7-8-9-16": {
    bigNumber: 16,
    tiles: [9, 5, 8, 6, 7],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 7,
        symbol: "add",
        tile2: 9,
        remainingTiles: [8, 5, 6, 16],
      },
      {
        tile1: 16,
        symbol: "divide",
        tile2: 8,
        remainingTiles: [5, 6, 2],
      },
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 2,
        remainingTiles: [6, 10],
      },
      { tile1: 6, symbol: "add", tile2: 10, remainingTiles: [16] },
    ],
  },
  "1-3-4-8-9-9": {
    bigNumber: 9,
    tiles: [8, 4, 9, 3, 1],
    symbols: { add: 2, subtract: 2, multiply: 0, divide: 0 },
    solution: [
      {
        tile1: 1,
        symbol: "add",
        tile2: 3,
        remainingTiles: [8, 4, 9, 4],
      },
      { tile1: 4, symbol: "add", tile2: 9, remainingTiles: [8, 4, 13] },
      {
        tile1: 8,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [13, 4],
      },
      { tile1: 13, symbol: "subtract", tile2: 4, remainingTiles: [9] },
    ],
  },
  "2-4-7-9-9-9": {
    bigNumber: 9,
    tiles: [9, 2, 9, 7, 4],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [9, 4, 2, 63],
      },
      { tile1: 4, symbol: "add", tile2: 2, remainingTiles: [9, 63, 6] },
      {
        tile1: 6,
        symbol: "multiply",
        tile2: 9,
        remainingTiles: [63, 54],
      },
      { tile1: 63, symbol: "subtract", tile2: 54, remainingTiles: [9] },
    ],
  },
  "1-4-4-5-7-60": {
    bigNumber: 60,
    tiles: [4, 5, 1, 7, 4],
    symbols: { add: 0, subtract: 1, multiply: 3, divide: 0 },
    solution: [
      {
        tile1: 1,
        symbol: "multiply",
        tile2: 7,
        remainingTiles: [5, 4, 4, 7],
      },
      {
        tile1: 7,
        symbol: "subtract",
        tile2: 4,
        remainingTiles: [5, 4, 3],
      },
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [3, 20],
      },
      { tile1: 3, symbol: "multiply", tile2: 20, remainingTiles: [60] },
    ],
  },
  "1-4-7-7-8-29": {
    bigNumber: 29,
    tiles: [7, 1, 7, 4, 8],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      {
        tile1: 7,
        symbol: "multiply",
        tile2: 4,
        remainingTiles: [7, 8, 1, 28],
      },
      {
        tile1: 28,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [7, 8, 28],
      },
      { tile1: 8, symbol: "add", tile2: 28, remainingTiles: [7, 36] },
      { tile1: 36, symbol: "subtract", tile2: 7, remainingTiles: [29] },
    ],
  },
  "2-3-4-4-9-2": {
    bigNumber: 2,
    tiles: [2, 3, 4, 4, 9],
    symbols: { add: 2, subtract: 0, multiply: 0, divide: 2 },
    solution: [
      {
        tile1: 3,
        symbol: "add",
        tile2: 9,
        remainingTiles: [4, 4, 2, 12],
      },
      {
        tile1: 12,
        symbol: "add",
        tile2: 4,
        remainingTiles: [4, 2, 16],
      },
      { tile1: 16, symbol: "divide", tile2: 2, remainingTiles: [4, 8] },
      { tile1: 8, symbol: "divide", tile2: 4, remainingTiles: [2] },
    ],
  },
  "1-5-6-8-8-53": {
    bigNumber: 53,
    tiles: [5, 8, 1, 8, 6],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      {
        tile1: 6,
        symbol: "subtract",
        tile2: 1,
        remainingTiles: [5, 8, 8, 5],
      },
      {
        tile1: 5,
        symbol: "multiply",
        tile2: 8,
        remainingTiles: [5, 8, 40],
      },
      { tile1: 8, symbol: "add", tile2: 40, remainingTiles: [5, 48] },
      { tile1: 48, symbol: "add", tile2: 5, remainingTiles: [53] },
    ],
  },
  "1-2-3-8-9-13": {
    bigNumber: 13,
    tiles: [1, 8, 2, 9, 3],
    symbols: { add: 0, subtract: 1, multiply: 2, divide: 1 },
    solution: [
      {
        tile1: 2,
        symbol: "multiply",
        tile2: 1,
        remainingTiles: [8, 9, 3, 2],
      },
      {
        tile1: 8,
        symbol: "multiply",
        tile2: 2,
        remainingTiles: [9, 3, 16],
      },
      { tile1: 9, symbol: "divide", tile2: 3, remainingTiles: [16, 3] },
      { tile1: 16, symbol: "subtract", tile2: 3, remainingTiles: [13] },
    ],
  },
  "3-5-5-7-8-22": {
    bigNumber: 22,
    tiles: [5, 8, 5, 7, 3],
    symbols: { add: 3, subtract: 1, multiply: 0, divide: 0 },
    solution: [
      {
        tile1: 5,
        symbol: "subtract",
        tile2: 3,
        remainingTiles: [7, 8, 5, 2],
      },
      { tile1: 7, symbol: "add", tile2: 5, remainingTiles: [8, 2, 12] },
      { tile1: 12, symbol: "add", tile2: 8, remainingTiles: [2, 20] },
      { tile1: 2, symbol: "add", tile2: 20, remainingTiles: [22] },
    ],
  },
  "1-2-3-4-5-7": {
    bigNumber: 7,
    tiles: [4, 5, 3, 1, 2],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      {
        tile1: 4,
        symbol: "subtract",
        tile2: 3,
        remainingTiles: [1, 5, 2, 1],
      },
      {
        tile1: 1,
        symbol: "divide",
        tile2: 1,
        remainingTiles: [5, 2, 1],
      },
      { tile1: 5, symbol: "add", tile2: 2, remainingTiles: [1, 7] },
      { tile1: 7, symbol: "multiply", tile2: 1, remainingTiles: [7] },
    ],
  },
};
