export const mediumPuzzles = {
  1: {
    bigNumber: 36,
    tiles: [8, 6, 9, 9, 8],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 8, symbol: "divide", tile2: 8 },
      { tile1: 1, symbol: "add", tile2: 9 },
      { tile1: 10, symbol: "subtract", tile2: 6 },
      { tile1: 4, symbol: "multiply", tile2: 9 },
    ],
  },
  2: {
    bigNumber: 61,
    tiles: [5, 9, 6, 4, 6],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 9, symbol: "add", tile2: 6 },
      { tile1: 15, symbol: "multiply", tile2: 4 },
      { tile1: 60, symbol: "add", tile2: 6 },
      { tile1: 66, symbol: "subtract", tile2: 5 },
    ],
  },
  3: {
    bigNumber: 8,
    tiles: [2, 1, 3, 7, 5],
    symbols: { add: 1, subtract: 1, multiply: 0, divide: 2 },
    solution: [
      { tile1: 5, symbol: "divide", tile2: 1 },
      { tile1: 5, symbol: "subtract", tile2: 2 },
      { tile1: 3, symbol: "divide", tile2: 3 },
      { tile1: 1, symbol: "add", tile2: 7 },
    ],
  },
  4: {
    bigNumber: 28,
    tiles: [8, 8, 5, 1, 8],
    symbols: { add: 3, subtract: 1, multiply: 0, divide: 0 },
    solution: [
      { tile1: 5, symbol: "add", tile2: 8 },
      { tile1: 13, symbol: "add", tile2: 8 },
      { tile1: 21, symbol: "add", tile2: 8 },
      { tile1: 29, symbol: "subtract", tile2: 1 },
    ],
  },
  5: {
    bigNumber: 88,
    tiles: [9, 1, 8, 7, 1],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 8, symbol: "divide", tile2: 1 },
      { tile1: 8, symbol: "add", tile2: 1 },
      { tile1: 9, symbol: "multiply", tile2: 9 },
      { tile1: 81, symbol: "add", tile2: 7 },
    ],
  },
  6: {
    bigNumber: 8,
    tiles: [2, 4, 1, 4, 6],
    symbols: { add: 1, subtract: 0, multiply: 1, divide: 2 },
    solution: [
      { tile1: 4, symbol: "multiply", tile2: 2 },
      { tile1: 8, symbol: "divide", tile2: 4 },
      { tile1: 2, symbol: "add", tile2: 6 },
      { tile1: 8, symbol: "divide", tile2: 1 },
    ],
  },
  7: {
    bigNumber: 86,
    tiles: [9, 9, 7, 3, 8],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 9, symbol: "divide", tile2: 3 },
      { tile1: 3, symbol: "add", tile2: 8 },
      { tile1: 11, symbol: "multiply", tile2: 7 },
      { tile1: 77, symbol: "add", tile2: 9 },
    ],
  },
  8: {
    bigNumber: 15,
    tiles: [2, 3, 9, 4, 3],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 4, symbol: "add", tile2: 9 },
      { tile1: 13, symbol: "subtract", tile2: 3 },
      { tile1: 10, symbol: "divide", tile2: 2 },
      { tile1: 5, symbol: "multiply", tile2: 3 },
    ],
  },
  9: {
    bigNumber: 47,
    tiles: [4, 2, 8, 1, 9],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 1, symbol: "add", tile2: 4 },
      { tile1: 5, symbol: "add", tile2: 2 },
      { tile1: 7, symbol: "multiply", tile2: 8 },
      { tile1: 56, symbol: "subtract", tile2: 9 },
    ],
  },
  10: {
    bigNumber: 12,
    tiles: [1, 4, 9, 8, 2],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 2, symbol: "multiply", tile2: 8 },
      { tile1: 16, symbol: "add", tile2: 4 },
      { tile1: 20, symbol: "add", tile2: 1 },
      { tile1: 21, symbol: "subtract", tile2: 9 },
    ],
  },
  11: {
    bigNumber: 56,
    tiles: [4, 1, 1, 8, 3],
    symbols: { add: 1, subtract: 0, multiply: 3, divide: 0 },
    solution: [
      { tile1: 3, symbol: "multiply", tile2: 1 },
      { tile1: 3, symbol: "multiply", tile2: 1 },
      { tile1: 3, symbol: "add", tile2: 4 },
      { tile1: 7, symbol: "multiply", tile2: 8 },
    ],
  },
  12: {
    bigNumber: 12,
    tiles: [7, 3, 4, 3, 5],
    symbols: { add: 0, subtract: 2, multiply: 2, divide: 0 },
    solution: [
      { tile1: 3, symbol: "multiply", tile2: 5 },
      { tile1: 15, symbol: "subtract", tile2: 4 },
      { tile1: 11, symbol: "subtract", tile2: 7 },
      { tile1: 4, symbol: "multiply", tile2: 3 },
    ],
  },
  13: {
    bigNumber: 10,
    tiles: [4, 1, 5, 8, 1],
    symbols: { add: 0, subtract: 0, multiply: 2, divide: 2 },
    solution: [
      { tile1: 5, symbol: "divide", tile2: 1 },
      { tile1: 5, symbol: "multiply", tile2: 1 },
      { tile1: 5, symbol: "multiply", tile2: 8 },
      { tile1: 40, symbol: "divide", tile2: 4 },
    ],
  },
  14: {
    bigNumber: 8,
    tiles: [7, 7, 1, 7, 1],
    symbols: { add: 2, subtract: 1, multiply: 0, divide: 1 },
    solution: [
      { tile1: 7, symbol: "add", tile2: 1 },
      { tile1: 8, symbol: "divide", tile2: 1 },
      { tile1: 8, symbol: "add", tile2: 7 },
      { tile1: 15, symbol: "subtract", tile2: 7 },
    ],
  },
  15: {
    bigNumber: 46,
    tiles: [7, 1, 7, 1, 3],
    symbols: { add: 0, subtract: 1, multiply: 1, divide: 2 },
    solution: [
      { tile1: 7, symbol: "divide", tile2: 1 },
      { tile1: 7, symbol: "divide", tile2: 1 },
      { tile1: 7, symbol: "multiply", tile2: 7 },
      { tile1: 49, symbol: "subtract", tile2: 3 },
    ],
  },
  16: {
    bigNumber: 87,
    tiles: [3, 3, 6, 3, 6],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      { tile1: 3, symbol: "add", tile2: 6 },
      { tile1: 9, symbol: "multiply", tile2: 3 },
      { tile1: 27, symbol: "multiply", tile2: 3 },
      { tile1: 81, symbol: "add", tile2: 6 },
    ],
  },
  17: {
    bigNumber: 43,
    tiles: [4, 4, 3, 1, 5],
    symbols: { add: 0, subtract: 1, multiply: 3, divide: 0 },
    solution: [
      { tile1: 4, symbol: "multiply", tile2: 3 },
      { tile1: 12, symbol: "multiply", tile2: 4 },
      { tile1: 48, symbol: "subtract", tile2: 5 },
      { tile1: 43, symbol: "multiply", tile2: 1 },
    ],
  },
  18: {
    bigNumber: 69,
    tiles: [8, 6, 2, 1, 9],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 8, symbol: "multiply", tile2: 9 },
      { tile1: 72, symbol: "add", tile2: 2 },
      { tile1: 74, symbol: "subtract", tile2: 6 },
      { tile1: 68, symbol: "add", tile2: 1 },
    ],
  },
  19: {
    bigNumber: 8,
    tiles: [3, 8, 4, 2, 4],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 4, symbol: "subtract", tile2: 3 },
      { tile1: 1, symbol: "multiply", tile2: 8 },
      { tile1: 8, symbol: "divide", tile2: 2 },
      { tile1: 4, symbol: "add", tile2: 4 },
    ],
  },
  20: {
    bigNumber: 80,
    tiles: [4, 1, 1, 4, 5],
    symbols: { add: 0, subtract: 0, multiply: 4, divide: 0 },
    solution: [
      { tile1: 4, symbol: "multiply", tile2: 4 },
      { tile1: 16, symbol: "multiply", tile2: 5 },
      { tile1: 80, symbol: "multiply", tile2: 1 },
      { tile1: 80, symbol: "multiply", tile2: 1 },
    ],
  },
  21: {
    bigNumber: 1,
    tiles: [4, 9, 1, 4, 1],
    symbols: { add: 0, subtract: 2, multiply: 1, divide: 1 },
    solution: [
      { tile1: 9, symbol: "multiply", tile2: 1 },
      { tile1: 9, symbol: "subtract", tile2: 4 },
      { tile1: 5, symbol: "subtract", tile2: 4 },
      { tile1: 1, symbol: "divide", tile2: 1 },
    ],
  },
  22: {
    bigNumber: 10,
    tiles: [2, 4, 4, 9, 3],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 2, symbol: "multiply", tile2: 4 },
      { tile1: 8, symbol: "add", tile2: 9 },
      { tile1: 17, symbol: "subtract", tile2: 4 },
      { tile1: 13, symbol: "subtract", tile2: 3 },
    ],
  },
  23: {
    bigNumber: 6,
    tiles: [8, 7, 9, 4, 6],
    symbols: { add: 2, subtract: 2, multiply: 0, divide: 0 },
    solution: [
      { tile1: 9, symbol: "add", tile2: 4 },
      { tile1: 13, symbol: "subtract", tile2: 6 },
      { tile1: 7, symbol: "add", tile2: 7 },
      { tile1: 14, symbol: "subtract", tile2: 8 },
    ],
  },
  24: {
    bigNumber: 15,
    tiles: [2, 2, 4, 8, 6],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 6, symbol: "multiply", tile2: 4 },
      { tile1: 24, symbol: "subtract", tile2: 2 },
      { tile1: 22, symbol: "add", tile2: 8 },
      { tile1: 30, symbol: "divide", tile2: 2 },
    ],
  },
  25: {
    bigNumber: 6,
    tiles: [5, 1, 2, 7, 9],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 7, symbol: "add", tile2: 2 },
      { tile1: 9, symbol: "divide", tile2: 9 },
      { tile1: 1, symbol: "multiply", tile2: 1 },
      { tile1: 1, symbol: "add", tile2: 5 },
    ],
  },
  26: {
    bigNumber: 46,
    tiles: [8, 3, 4, 4, 1],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 4, symbol: "add", tile2: 8 },
      { tile1: 12, symbol: "multiply", tile2: 4 },
      { tile1: 48, symbol: "subtract", tile2: 3 },
      { tile1: 45, symbol: "add", tile2: 1 },
    ],
  },
  27: {
    bigNumber: 28,
    tiles: [7, 3, 4, 7, 4],
    symbols: { add: 0, subtract: 1, multiply: 2, divide: 1 },
    solution: [
      { tile1: 7, symbol: "subtract", tile2: 3 },
      { tile1: 4, symbol: "divide", tile2: 4 },
      { tile1: 1, symbol: "multiply", tile2: 7 },
      { tile1: 7, symbol: "multiply", tile2: 4 },
    ],
  },
  28: {
    bigNumber: 20,
    tiles: [4, 4, 5, 6, 3],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 3, symbol: "add", tile2: 5 },
      { tile1: 8, symbol: "subtract", tile2: 4 },
      { tile1: 4, symbol: "multiply", tile2: 6 },
      { tile1: 24, symbol: "subtract", tile2: 4 },
    ],
  },
  29: {
    bigNumber: 6,
    tiles: [5, 2, 3, 2, 4],
    symbols: { add: 3, subtract: 0, multiply: 0, divide: 1 },
    solution: [
      { tile1: 3, symbol: "add", tile2: 5 },
      { tile1: 8, symbol: "divide", tile2: 4 },
      { tile1: 2, symbol: "add", tile2: 2 },
      { tile1: 4, symbol: "add", tile2: 2 },
    ],
  },
  30: {
    bigNumber: 3,
    tiles: [1, 5, 4, 7, 6],
    symbols: { add: 1, subtract: 3, multiply: 0, divide: 0 },
    solution: [
      { tile1: 7, symbol: "subtract", tile2: 4 },
      { tile1: 3, symbol: "add", tile2: 6 },
      { tile1: 9, symbol: "subtract", tile2: 1 },
      { tile1: 8, symbol: "subtract", tile2: 5 },
    ],
  },
  31: {
    bigNumber: 12,
    tiles: [3, 3, 9, 4, 2],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 2, symbol: "add", tile2: 3 },
      { tile1: 5, symbol: "multiply", tile2: 9 },
      { tile1: 45, symbol: "add", tile2: 3 },
      { tile1: 48, symbol: "divide", tile2: 4 },
    ],
  },
  32: {
    bigNumber: 49,
    tiles: [4, 4, 7, 8, 7],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 7, symbol: "multiply", tile2: 7 },
      { tile1: 49, symbol: "subtract", tile2: 4 },
      { tile1: 45, symbol: "subtract", tile2: 4 },
      { tile1: 41, symbol: "add", tile2: 8 },
    ],
  },
  33: {
    bigNumber: 43,
    tiles: [3, 4, 2, 5, 2],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      { tile1: 2, symbol: "add", tile2: 4 },
      { tile1: 6, symbol: "add", tile2: 2 },
      { tile1: 8, symbol: "multiply", tile2: 5 },
      { tile1: 40, symbol: "add", tile2: 3 },
    ],
  },
  34: {
    bigNumber: 5,
    tiles: [1, 1, 1, 3, 2],
    symbols: { add: 2, subtract: 1, multiply: 0, divide: 1 },
    solution: [
      { tile1: 3, symbol: "add", tile2: 1 },
      { tile1: 4, symbol: "divide", tile2: 1 },
      { tile1: 4, symbol: "add", tile2: 2 },
      { tile1: 6, symbol: "subtract", tile2: 1 },
    ],
  },
  35: {
    bigNumber: 50,
    tiles: [1, 2, 9, 2, 5],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      { tile1: 2, symbol: "multiply", tile2: 2 },
      { tile1: 4, symbol: "add", tile2: 1 },
      { tile1: 5, symbol: "multiply", tile2: 9 },
      { tile1: 45, symbol: "add", tile2: 5 },
    ],
  },
  36: {
    bigNumber: 8,
    tiles: [2, 8, 8, 1, 5],
    symbols: { add: 0, subtract: 2, multiply: 1, divide: 1 },
    solution: [
      { tile1: 8, symbol: "subtract", tile2: 5 },
      { tile1: 3, symbol: "subtract", tile2: 1 },
      { tile1: 2, symbol: "divide", tile2: 2 },
      { tile1: 1, symbol: "multiply", tile2: 8 },
    ],
  },
  37: {
    bigNumber: 39,
    tiles: [3, 4, 7, 7, 3],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 3, symbol: "divide", tile2: 3 },
      { tile1: 1, symbol: "add", tile2: 7 },
      { tile1: 8, symbol: "multiply", tile2: 4 },
      { tile1: 32, symbol: "add", tile2: 7 },
    ],
  },
  38: {
    bigNumber: 4,
    tiles: [8, 5, 4, 9, 4],
    symbols: { add: 2, subtract: 0, multiply: 0, divide: 2 },
    solution: [
      { tile1: 8, symbol: "divide", tile2: 4 },
      { tile1: 2, symbol: "add", tile2: 5 },
      { tile1: 7, symbol: "add", tile2: 9 },
      { tile1: 16, symbol: "divide", tile2: 4 },
    ],
  },
  39: {
    bigNumber: 1,
    tiles: [6, 4, 5, 2, 7],
    symbols: { add: 0, subtract: 2, multiply: 1, divide: 1 },
    solution: [
      { tile1: 7, symbol: "subtract", tile2: 5 },
      { tile1: 2, symbol: "multiply", tile2: 4 },
      { tile1: 8, symbol: "subtract", tile2: 6 },
      { tile1: 2, symbol: "divide", tile2: 2 },
    ],
  },
  40: {
    bigNumber: 30,
    tiles: [4, 9, 2, 6, 2],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 4, symbol: "multiply", tile2: 9 },
      { tile1: 36, symbol: "subtract", tile2: 6 },
      { tile1: 30, symbol: "subtract", tile2: 2 },
      { tile1: 28, symbol: "add", tile2: 2 },
    ],
  },
  41: {
    bigNumber: 6,
    tiles: [1, 2, 2, 1, 4],
    symbols: { add: 2, subtract: 0, multiply: 0, divide: 2 },
    solution: [
      { tile1: 2, symbol: "divide", tile2: 1 },
      { tile1: 2, symbol: "divide", tile2: 2 },
      { tile1: 1, symbol: "add", tile2: 4 },
      { tile1: 5, symbol: "add", tile2: 1 },
    ],
  },
  42: {
    bigNumber: 27,
    tiles: [5, 8, 8, 1, 5],
    symbols: { add: 4, subtract: 0, multiply: 0, divide: 0 },
    solution: [
      { tile1: 5, symbol: "add", tile2: 8 },
      { tile1: 13, symbol: "add", tile2: 5 },
      { tile1: 18, symbol: "add", tile2: 1 },
      { tile1: 19, symbol: "add", tile2: 8 },
    ],
  },
  43: {
    bigNumber: 3,
    tiles: [7, 6, 2, 8, 9],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 2, symbol: "add", tile2: 7 },
      { tile1: 9, symbol: "subtract", tile2: 8 },
      { tile1: 1, symbol: "multiply", tile2: 9 },
      { tile1: 9, symbol: "subtract", tile2: 6 },
    ],
  },
  44: {
    bigNumber: 9,
    tiles: [4, 2, 1, 1, 8],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 4, symbol: "subtract", tile2: 2 },
      { tile1: 2, symbol: "subtract", tile2: 1 },
      { tile1: 1, symbol: "multiply", tile2: 8 },
      { tile1: 8, symbol: "add", tile2: 1 },
    ],
  },
  45: {
    bigNumber: 26,
    tiles: [6, 4, 1, 6, 9],
    symbols: { add: 4, subtract: 0, multiply: 0, divide: 0 },
    solution: [
      { tile1: 4, symbol: "add", tile2: 6 },
      { tile1: 10, symbol: "add", tile2: 9 },
      { tile1: 19, symbol: "add", tile2: 6 },
      { tile1: 25, symbol: "add", tile2: 1 },
    ],
  },
  46: {
    bigNumber: 25,
    tiles: [3, 2, 7, 6, 1],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 3, symbol: "multiply", tile2: 7 },
      { tile1: 21, symbol: "subtract", tile2: 2 },
      { tile1: 19, symbol: "divide", tile2: 1 },
      { tile1: 19, symbol: "add", tile2: 6 },
    ],
  },
  47: {
    bigNumber: 16,
    tiles: [1, 6, 2, 1, 2],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      { tile1: 2, symbol: "divide", tile2: 1 },
      { tile1: 2, symbol: "add", tile2: 6 },
      { tile1: 8, symbol: "multiply", tile2: 1 },
      { tile1: 8, symbol: "multiply", tile2: 2 },
    ],
  },
  48: {
    bigNumber: 4,
    tiles: [2, 1, 4, 4, 2],
    symbols: { add: 0, subtract: 0, multiply: 1, divide: 3 },
    solution: [
      { tile1: 4, symbol: "divide", tile2: 2 },
      { tile1: 2, symbol: "divide", tile2: 1 },
      { tile1: 2, symbol: "divide", tile2: 2 },
      { tile1: 1, symbol: "multiply", tile2: 4 },
    ],
  },
  49: {
    bigNumber: 33,
    tiles: [3, 2, 1, 7, 8],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 7, symbol: "add", tile2: 8 },
      { tile1: 15, symbol: "multiply", tile2: 2 },
      { tile1: 30, symbol: "divide", tile2: 1 },
      { tile1: 30, symbol: "add", tile2: 3 },
    ],
  },
  50: {
    bigNumber: 19,
    tiles: [3, 4, 2, 8, 4],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      { tile1: 4, symbol: "multiply", tile2: 8 },
      { tile1: 32, symbol: "divide", tile2: 4 },
      { tile1: 8, symbol: "multiply", tile2: 2 },
      { tile1: 16, symbol: "add", tile2: 3 },
    ],
  },
  51: {
    bigNumber: 2,
    tiles: [2, 8, 4, 1, 4],
    symbols: { add: 2, subtract: 0, multiply: 0, divide: 2 },
    solution: [
      { tile1: 4, symbol: "add", tile2: 8 },
      { tile1: 12, symbol: "divide", tile2: 4 },
      { tile1: 3, symbol: "add", tile2: 1 },
      { tile1: 4, symbol: "divide", tile2: 2 },
    ],
  },
  52: {
    bigNumber: 3,
    tiles: [3, 3, 3, 1, 9],
    symbols: { add: 0, subtract: 0, multiply: 2, divide: 2 },
    solution: [
      { tile1: 3, symbol: "divide", tile2: 3 },
      { tile1: 1, symbol: "multiply", tile2: 1 },
      { tile1: 1, symbol: "multiply", tile2: 9 },
      { tile1: 9, symbol: "divide", tile2: 3 },
    ],
  },
  53: {
    bigNumber: 16,
    tiles: [7, 4, 7, 1, 3],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      { tile1: 3, symbol: "add", tile2: 1 },
      { tile1: 4, symbol: "multiply", tile2: 7 },
      { tile1: 28, symbol: "divide", tile2: 7 },
      { tile1: 4, symbol: "multiply", tile2: 4 },
    ],
  },
  54: {
    bigNumber: 7,
    tiles: [8, 1, 6, 2, 4],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      { tile1: 6, symbol: "add", tile2: 8 },
      { tile1: 14, symbol: "multiply", tile2: 1 },
      { tile1: 14, symbol: "multiply", tile2: 2 },
      { tile1: 28, symbol: "divide", tile2: 4 },
    ],
  },
  55: {
    bigNumber: 7,
    tiles: [2, 5, 5, 1, 4],
    symbols: { add: 0, subtract: 1, multiply: 2, divide: 1 },
    solution: [
      { tile1: 2, symbol: "multiply", tile2: 5 },
      { tile1: 10, symbol: "divide", tile2: 5 },
      { tile1: 2, symbol: "multiply", tile2: 4 },
      { tile1: 8, symbol: "subtract", tile2: 1 },
    ],
  },
  56: {
    bigNumber: 9,
    tiles: [4, 4, 4, 9, 4],
    symbols: { add: 0, subtract: 0, multiply: 2, divide: 2 },
    solution: [
      { tile1: 4, symbol: "divide", tile2: 4 },
      { tile1: 1, symbol: "multiply", tile2: 4 },
      { tile1: 4, symbol: "multiply", tile2: 9 },
      { tile1: 36, symbol: "divide", tile2: 4 },
    ],
  },
  57: {
    bigNumber: 15,
    tiles: [1, 7, 2, 2, 8],
    symbols: { add: 1, subtract: 0, multiply: 1, divide: 2 },
    solution: [
      { tile1: 8, symbol: "divide", tile2: 2 },
      { tile1: 4, symbol: "multiply", tile2: 2 },
      { tile1: 8, symbol: "add", tile2: 7 },
      { tile1: 15, symbol: "divide", tile2: 1 },
    ],
  },
  58: {
    bigNumber: 11,
    tiles: [4, 7, 7, 4, 3],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 7, symbol: "subtract", tile2: 3 },
      { tile1: 4, symbol: "divide", tile2: 4 },
      { tile1: 1, symbol: "multiply", tile2: 4 },
      { tile1: 4, symbol: "add", tile2: 7 },
    ],
  },
  59: {
    bigNumber: 8,
    tiles: [2, 8, 1, 1, 2],
    symbols: { add: 2, subtract: 2, multiply: 0, divide: 0 },
    solution: [
      { tile1: 1, symbol: "add", tile2: 2 },
      { tile1: 3, symbol: "subtract", tile2: 2 },
      { tile1: 1, symbol: "add", tile2: 8 },
      { tile1: 9, symbol: "subtract", tile2: 1 },
    ],
  },
  60: {
    bigNumber: 9,
    tiles: [9, 5, 2, 2, 1],
    symbols: { add: 0, subtract: 2, multiply: 1, divide: 1 },
    solution: [
      { tile1: 5, symbol: "subtract", tile2: 2 },
      { tile1: 3, symbol: "divide", tile2: 1 },
      { tile1: 3, symbol: "subtract", tile2: 2 },
      { tile1: 1, symbol: "multiply", tile2: 9 },
    ],
  },
  61: {
    bigNumber: 44,
    tiles: [5, 2, 3, 7, 4],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      { tile1: 7, symbol: "multiply", tile2: 5 },
      { tile1: 35, symbol: "add", tile2: 4 },
      { tile1: 39, symbol: "add", tile2: 2 },
      { tile1: 41, symbol: "add", tile2: 3 },
    ],
  },
  62: {
    bigNumber: 61,
    tiles: [1, 7, 6, 9, 8],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      { tile1: 1, symbol: "multiply", tile2: 7 },
      { tile1: 7, symbol: "multiply", tile2: 9 },
      { tile1: 63, symbol: "subtract", tile2: 8 },
      { tile1: 55, symbol: "add", tile2: 6 },
    ],
  },
  63: {
    bigNumber: 1,
    tiles: [3, 1, 5, 4, 2],
    symbols: { add: 2, subtract: 2, multiply: 0, divide: 0 },
    solution: [
      { tile1: 2, symbol: "add", tile2: 5 },
      { tile1: 7, symbol: "subtract", tile2: 3 },
      { tile1: 4, symbol: "add", tile2: 1 },
      { tile1: 5, symbol: "subtract", tile2: 4 },
    ],
  },
  64: {
    bigNumber: 98,
    tiles: [5, 8, 6, 7, 5],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      { tile1: 5, symbol: "add", tile2: 7 },
      { tile1: 12, symbol: "add", tile2: 6 },
      { tile1: 18, symbol: "multiply", tile2: 5 },
      { tile1: 90, symbol: "add", tile2: 8 },
    ],
  },
  65: {
    bigNumber: 1,
    tiles: [1, 7, 7, 1, 1],
    symbols: { add: 0, subtract: 0, multiply: 0, divide: 4 },
    solution: [
      { tile1: 7, symbol: "divide", tile2: 7 },
      { tile1: 1, symbol: "divide", tile2: 1 },
      { tile1: 1, symbol: "divide", tile2: 1 },
      { tile1: 1, symbol: "divide", tile2: 1 },
    ],
  },
  66: {
    bigNumber: 1,
    tiles: [1, 5, 1, 7, 1],
    symbols: { add: 0, subtract: 2, multiply: 2, divide: 0 },
    solution: [
      { tile1: 1, symbol: "multiply", tile2: 7 },
      { tile1: 7, symbol: "subtract", tile2: 5 },
      { tile1: 2, symbol: "subtract", tile2: 1 },
      { tile1: 1, symbol: "multiply", tile2: 1 },
    ],
  },
  67: {
    bigNumber: 6,
    tiles: [1, 1, 5, 1, 1],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      { tile1: 1, symbol: "add", tile2: 5 },
      { tile1: 6, symbol: "multiply", tile2: 1 },
      { tile1: 6, symbol: "divide", tile2: 1 },
      { tile1: 6, symbol: "multiply", tile2: 1 },
    ],
  },
  68: {
    bigNumber: 8,
    tiles: [3, 2, 1, 4, 5],
    symbols: { add: 3, subtract: 0, multiply: 0, divide: 1 },
    solution: [
      { tile1: 5, symbol: "add", tile2: 4 },
      { tile1: 9, symbol: "add", tile2: 1 },
      { tile1: 10, symbol: "divide", tile2: 2 },
      { tile1: 5, symbol: "add", tile2: 3 },
    ],
  },
  69: {
    bigNumber: 54,
    tiles: [1, 9, 5, 6, 6],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 6, symbol: "multiply", tile2: 9 },
      { tile1: 54, symbol: "add", tile2: 5 },
      { tile1: 59, symbol: "add", tile2: 1 },
      { tile1: 60, symbol: "subtract", tile2: 6 },
    ],
  },
  70: {
    bigNumber: 24,
    tiles: [5, 9, 1, 3, 1],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      { tile1: 3, symbol: "multiply", tile2: 1 },
      { tile1: 3, symbol: "multiply", tile2: 5 },
      { tile1: 15, symbol: "add", tile2: 9 },
      { tile1: 24, symbol: "divide", tile2: 1 },
    ],
  },
  71: {
    bigNumber: 14,
    tiles: [1, 7, 5, 7, 8],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 7, symbol: "multiply", tile2: 5 },
      { tile1: 35, symbol: "divide", tile2: 7 },
      { tile1: 5, symbol: "add", tile2: 1 },
      { tile1: 6, symbol: "add", tile2: 8 },
    ],
  },
  72: {
    bigNumber: 2,
    tiles: [3, 1, 2, 1, 1],
    symbols: { add: 1, subtract: 1, multiply: 0, divide: 2 },
    solution: [
      { tile1: 3, symbol: "subtract", tile2: 2 },
      { tile1: 1, symbol: "add", tile2: 1 },
      { tile1: 2, symbol: "divide", tile2: 1 },
      { tile1: 2, symbol: "divide", tile2: 1 },
    ],
  },
  73: {
    bigNumber: 13,
    tiles: [2, 8, 2, 4, 6],
    symbols: { add: 3, subtract: 0, multiply: 0, divide: 1 },
    solution: [
      { tile1: 8, symbol: "add", tile2: 4 },
      { tile1: 12, symbol: "add", tile2: 2 },
      { tile1: 14, symbol: "divide", tile2: 2 },
      { tile1: 7, symbol: "add", tile2: 6 },
    ],
  },
  74: {
    bigNumber: 15,
    tiles: [5, 7, 5, 1, 1],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      { tile1: 1, symbol: "multiply", tile2: 1 },
      { tile1: 1, symbol: "add", tile2: 7 },
      { tile1: 8, symbol: "subtract", tile2: 5 },
      { tile1: 3, symbol: "multiply", tile2: 5 },
    ],
  },
  75: {
    bigNumber: 7,
    tiles: [2, 2, 2, 1, 1],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      { tile1: 2, symbol: "add", tile2: 2 },
      { tile1: 4, symbol: "add", tile2: 2 },
      { tile1: 6, symbol: "add", tile2: 1 },
      { tile1: 7, symbol: "multiply", tile2: 1 },
    ],
  },
  76: {
    bigNumber: 37,
    tiles: [9, 1, 7, 4, 6],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 4, symbol: "multiply", tile2: 9 },
      { tile1: 36, symbol: "add", tile2: 7 },
      { tile1: 43, symbol: "divide", tile2: 1 },
      { tile1: 43, symbol: "subtract", tile2: 6 },
    ],
  },
  77: {
    bigNumber: 16,
    tiles: [2, 1, 3, 7, 2],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 3, symbol: "add", tile2: 7 },
      { tile1: 10, symbol: "divide", tile2: 1 },
      { tile1: 10, symbol: "subtract", tile2: 2 },
      { tile1: 8, symbol: "multiply", tile2: 2 },
    ],
  },
  78: {
    bigNumber: 8,
    tiles: [1, 3, 3, 2, 4],
    symbols: { add: 0, subtract: 0, multiply: 3, divide: 1 },
    solution: [
      { tile1: 3, symbol: "divide", tile2: 3 },
      { tile1: 1, symbol: "multiply", tile2: 1 },
      { tile1: 1, symbol: "multiply", tile2: 2 },
      { tile1: 2, symbol: "multiply", tile2: 4 },
    ],
  },
  79: {
    bigNumber: 45,
    tiles: [1, 5, 9, 2, 6],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 6, symbol: "add", tile2: 5 },
      { tile1: 11, symbol: "subtract", tile2: 1 },
      { tile1: 10, symbol: "multiply", tile2: 9 },
      { tile1: 90, symbol: "divide", tile2: 2 },
    ],
  },
  80: {
    bigNumber: 14,
    tiles: [2, 4, 1, 7, 5],
    symbols: { add: 2, subtract: 0, multiply: 0, divide: 2 },
    solution: [
      { tile1: 4, symbol: "divide", tile2: 2 },
      { tile1: 2, symbol: "divide", tile2: 1 },
      { tile1: 2, symbol: "add", tile2: 7 },
      { tile1: 9, symbol: "add", tile2: 5 },
    ],
  },
  81: {
    bigNumber: 12,
    tiles: [1, 3, 6, 9, 6],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 1, symbol: "multiply", tile2: 3 },
      { tile1: 3, symbol: "add", tile2: 6 },
      { tile1: 9, symbol: "add", tile2: 9 },
      { tile1: 18, symbol: "subtract", tile2: 6 },
    ],
  },
  82: {
    bigNumber: 4,
    tiles: [5, 3, 3, 1, 8],
    symbols: { add: 0, subtract: 2, multiply: 1, divide: 1 },
    solution: [
      { tile1: 3, symbol: "multiply", tile2: 5 },
      { tile1: 15, symbol: "subtract", tile2: 3 },
      { tile1: 12, symbol: "divide", tile2: 1 },
      { tile1: 12, symbol: "subtract", tile2: 8 },
    ],
  },
  83: {
    bigNumber: 22,
    tiles: [7, 7, 3, 2, 3],
    symbols: { add: 4, subtract: 0, multiply: 0, divide: 0 },
    solution: [
      { tile1: 3, symbol: "add", tile2: 3 },
      { tile1: 6, symbol: "add", tile2: 7 },
      { tile1: 13, symbol: "add", tile2: 7 },
      { tile1: 20, symbol: "add", tile2: 2 },
    ],
  },
  84: {
    bigNumber: 40,
    tiles: [2, 1, 5, 2, 8],
    symbols: { add: 0, subtract: 0, multiply: 2, divide: 2 },
    solution: [
      { tile1: 8, symbol: "divide", tile2: 1 },
      { tile1: 8, symbol: "multiply", tile2: 5 },
      { tile1: 40, symbol: "multiply", tile2: 2 },
      { tile1: 80, symbol: "divide", tile2: 2 },
    ],
  },
  85: {
    bigNumber: 36,
    tiles: [1, 4, 3, 5, 6],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      { tile1: 6, symbol: "add", tile2: 4 },
      { tile1: 10, symbol: "multiply", tile2: 3 },
      { tile1: 30, symbol: "add", tile2: 1 },
      { tile1: 31, symbol: "add", tile2: 5 },
    ],
  },
  86: {
    bigNumber: 46,
    tiles: [5, 4, 1, 7, 6],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      { tile1: 6, symbol: "add", tile2: 1 },
      { tile1: 7, symbol: "multiply", tile2: 5 },
      { tile1: 35, symbol: "add", tile2: 7 },
      { tile1: 42, symbol: "add", tile2: 4 },
    ],
  },
  87: {
    bigNumber: 3,
    tiles: [1, 3, 9, 9, 1],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      { tile1: 9, symbol: "multiply", tile2: 1 },
      { tile1: 9, symbol: "add", tile2: 1 },
      { tile1: 10, symbol: "subtract", tile2: 9 },
      { tile1: 1, symbol: "multiply", tile2: 3 },
    ],
  },
  88: {
    bigNumber: 35,
    tiles: [5, 7, 7, 7, 1],
    symbols: { add: 0, subtract: 0, multiply: 2, divide: 2 },
    solution: [
      { tile1: 7, symbol: "divide", tile2: 1 },
      { tile1: 7, symbol: "multiply", tile2: 7 },
      { tile1: 49, symbol: "divide", tile2: 7 },
      { tile1: 7, symbol: "multiply", tile2: 5 },
    ],
  },
  89: {
    bigNumber: 3,
    tiles: [8, 6, 3, 7, 6],
    symbols: { add: 2, subtract: 1, multiply: 0, divide: 1 },
    solution: [
      { tile1: 7, symbol: "subtract", tile2: 3 },
      { tile1: 4, symbol: "add", tile2: 8 },
      { tile1: 12, symbol: "add", tile2: 6 },
      { tile1: 18, symbol: "divide", tile2: 6 },
    ],
  },
  90: {
    bigNumber: 18,
    tiles: [9, 4, 2, 1, 4],
    symbols: { add: 0, subtract: 0, multiply: 2, divide: 2 },
    solution: [
      { tile1: 4, symbol: "divide", tile2: 1 },
      { tile1: 4, symbol: "multiply", tile2: 2 },
      { tile1: 8, symbol: "multiply", tile2: 9 },
      { tile1: 72, symbol: "divide", tile2: 4 },
    ],
  },
  91: {
    bigNumber: 9,
    tiles: [2, 5, 6, 6, 1],
    symbols: { add: 0, subtract: 1, multiply: 2, divide: 1 },
    solution: [
      { tile1: 1, symbol: "multiply", tile2: 5 },
      { tile1: 5, symbol: "multiply", tile2: 6 },
      { tile1: 30, symbol: "divide", tile2: 2 },
      { tile1: 15, symbol: "subtract", tile2: 6 },
    ],
  },
  92: {
    bigNumber: 11,
    tiles: [4, 3, 1, 6, 5],
    symbols: { add: 2, subtract: 2, multiply: 0, divide: 0 },
    solution: [
      { tile1: 5, symbol: "add", tile2: 4 },
      { tile1: 9, symbol: "add", tile2: 6 },
      { tile1: 15, symbol: "subtract", tile2: 3 },
      { tile1: 12, symbol: "subtract", tile2: 1 },
    ],
  },
  93: {
    bigNumber: 24,
    tiles: [4, 9, 4, 4, 2],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 9, symbol: "subtract", tile2: 4 },
      { tile1: 5, symbol: "add", tile2: 2 },
      { tile1: 7, symbol: "multiply", tile2: 4 },
      { tile1: 28, symbol: "subtract", tile2: 4 },
    ],
  },
  94: {
    bigNumber: 5,
    tiles: [3, 1, 5, 3, 5],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 5, symbol: "add", tile2: 1 },
      { tile1: 6, symbol: "subtract", tile2: 3 },
      { tile1: 3, symbol: "divide", tile2: 3 },
      { tile1: 1, symbol: "multiply", tile2: 5 },
    ],
  },
  95: {
    bigNumber: 12,
    tiles: [3, 3, 2, 2, 3],
    symbols: { add: 0, subtract: 0, multiply: 3, divide: 1 },
    solution: [
      { tile1: 2, symbol: "multiply", tile2: 3 },
      { tile1: 6, symbol: "multiply", tile2: 2 },
      { tile1: 12, symbol: "multiply", tile2: 3 },
      { tile1: 36, symbol: "divide", tile2: 3 },
    ],
  },
  96: {
    bigNumber: 8,
    tiles: [2, 3, 7, 9, 1],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      { tile1: 1, symbol: "multiply", tile2: 7 },
      { tile1: 7, symbol: "multiply", tile2: 2 },
      { tile1: 14, symbol: "subtract", tile2: 9 },
      { tile1: 5, symbol: "add", tile2: 3 },
    ],
  },
  97: {
    bigNumber: 7,
    tiles: [2, 2, 2, 9, 2],
    symbols: { add: 2, subtract: 0, multiply: 0, divide: 2 },
    solution: [
      { tile1: 2, symbol: "divide", tile2: 2 },
      { tile1: 1, symbol: "add", tile2: 9 },
      { tile1: 10, symbol: "divide", tile2: 2 },
      { tile1: 5, symbol: "add", tile2: 2 },
    ],
  },
  98: {
    bigNumber: 13,
    tiles: [7, 3, 3, 1, 2],
    symbols: { add: 0, subtract: 1, multiply: 2, divide: 1 },
    solution: [
      { tile1: 3, symbol: "divide", tile2: 3 },
      { tile1: 1, symbol: "multiply", tile2: 2 },
      { tile1: 2, symbol: "multiply", tile2: 7 },
      { tile1: 14, symbol: "subtract", tile2: 1 },
    ],
  },
  99: {
    bigNumber: 30,
    tiles: [7, 3, 8, 6, 6],
    symbols: { add: 4, subtract: 0, multiply: 0, divide: 0 },
    solution: [
      { tile1: 7, symbol: "add", tile2: 6 },
      { tile1: 13, symbol: "add", tile2: 3 },
      { tile1: 16, symbol: "add", tile2: 6 },
      { tile1: 22, symbol: "add", tile2: 8 },
    ],
  },
  100: {
    bigNumber: 10,
    tiles: [8, 9, 5, 5, 1],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      { tile1: 9, symbol: "multiply", tile2: 1 },
      { tile1: 9, symbol: "subtract", tile2: 8 },
      { tile1: 1, symbol: "multiply", tile2: 5 },
      { tile1: 5, symbol: "add", tile2: 5 },
    ],
  },
  101: {
    bigNumber: 32,
    tiles: [6, 2, 3, 1, 4],
    symbols: { add: 0, subtract: 1, multiply: 2, divide: 1 },
    solution: [
      { tile1: 3, symbol: "divide", tile2: 1 },
      { tile1: 3, symbol: "multiply", tile2: 6 },
      { tile1: 18, symbol: "multiply", tile2: 2 },
      { tile1: 36, symbol: "subtract", tile2: 4 },
    ],
  },
  102: {
    bigNumber: 16,
    tiles: [8, 1, 6, 6, 7],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 7, symbol: "add", tile2: 1 },
      { tile1: 8, symbol: "add", tile2: 8 },
      { tile1: 16, symbol: "multiply", tile2: 6 },
      { tile1: 96, symbol: "divide", tile2: 6 },
    ],
  },
  103: {
    bigNumber: 7,
    tiles: [8, 8, 5, 2, 1],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      { tile1: 8, symbol: "multiply", tile2: 2 },
      { tile1: 16, symbol: "divide", tile2: 8 },
      { tile1: 2, symbol: "multiply", tile2: 1 },
      { tile1: 2, symbol: "add", tile2: 5 },
    ],
  },
  104: {
    bigNumber: 11,
    tiles: [8, 4, 2, 2, 3],
    symbols: { add: 1, subtract: 0, multiply: 1, divide: 2 },
    solution: [
      { tile1: 4, symbol: "divide", tile2: 2 },
      { tile1: 2, symbol: "divide", tile2: 2 },
      { tile1: 1, symbol: "multiply", tile2: 8 },
      { tile1: 8, symbol: "add", tile2: 3 },
    ],
  },
  105: {
    bigNumber: 82,
    tiles: [5, 2, 6, 2, 4],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      { tile1: 2, symbol: "multiply", tile2: 5 },
      { tile1: 10, symbol: "add", tile2: 4 },
      { tile1: 14, symbol: "multiply", tile2: 6 },
      { tile1: 84, symbol: "subtract", tile2: 2 },
    ],
  },
  106: {
    bigNumber: 1,
    tiles: [9, 7, 1, 6, 5],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 1, symbol: "multiply", tile2: 5 },
      { tile1: 5, symbol: "add", tile2: 9 },
      { tile1: 14, symbol: "subtract", tile2: 7 },
      { tile1: 7, symbol: "subtract", tile2: 6 },
    ],
  },
  107: {
    bigNumber: 17,
    tiles: [3, 1, 6, 7, 7],
    symbols: { add: 2, subtract: 1, multiply: 0, divide: 1 },
    solution: [
      { tile1: 6, symbol: "subtract", tile2: 3 },
      { tile1: 3, symbol: "add", tile2: 7 },
      { tile1: 10, symbol: "add", tile2: 7 },
      { tile1: 17, symbol: "divide", tile2: 1 },
    ],
  },
  108: {
    bigNumber: 28,
    tiles: [6, 1, 4, 4, 5],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      { tile1: 6, symbol: "subtract", tile2: 4 },
      { tile1: 2, symbol: "add", tile2: 5 },
      { tile1: 7, symbol: "multiply", tile2: 1 },
      { tile1: 7, symbol: "multiply", tile2: 4 },
    ],
  },
  109: {
    bigNumber: 12,
    tiles: [6, 1, 9, 6, 2],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 1, symbol: "add", tile2: 6 },
      { tile1: 7, symbol: "multiply", tile2: 6 },
      { tile1: 42, symbol: "divide", tile2: 2 },
      { tile1: 21, symbol: "subtract", tile2: 9 },
    ],
  },
  110: {
    bigNumber: 63,
    tiles: [3, 5, 3, 7, 5],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      { tile1: 3, symbol: "multiply", tile2: 7 },
      { tile1: 21, symbol: "multiply", tile2: 3 },
      { tile1: 63, symbol: "subtract", tile2: 5 },
      { tile1: 58, symbol: "add", tile2: 5 },
    ],
  },
  111: {
    bigNumber: 15,
    tiles: [6, 4, 1, 8, 9],
    symbols: { add: 2, subtract: 1, multiply: 0, divide: 1 },
    solution: [
      { tile1: 8, symbol: "add", tile2: 9 },
      { tile1: 17, symbol: "divide", tile2: 1 },
      { tile1: 17, symbol: "subtract", tile2: 6 },
      { tile1: 11, symbol: "add", tile2: 4 },
    ],
  },
  112: {
    bigNumber: 8,
    tiles: [1, 5, 3, 9, 2],
    symbols: { add: 2, subtract: 1, multiply: 0, divide: 1 },
    solution: [
      { tile1: 5, symbol: "subtract", tile2: 1 },
      { tile1: 4, symbol: "add", tile2: 3 },
      { tile1: 7, symbol: "add", tile2: 9 },
      { tile1: 16, symbol: "divide", tile2: 2 },
    ],
  },
  113: {
    bigNumber: 1,
    tiles: [3, 7, 1, 1, 8],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 7, symbol: "add", tile2: 3 },
      { tile1: 10, symbol: "subtract", tile2: 1 },
      { tile1: 9, symbol: "subtract", tile2: 8 },
      { tile1: 1, symbol: "multiply", tile2: 1 },
    ],
  },
  114: {
    bigNumber: 11,
    tiles: [1, 3, 8, 8, 8],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 8, symbol: "add", tile2: 1 },
      { tile1: 9, symbol: "subtract", tile2: 8 },
      { tile1: 1, symbol: "multiply", tile2: 8 },
      { tile1: 8, symbol: "add", tile2: 3 },
    ],
  },
  115: {
    bigNumber: 56,
    tiles: [6, 2, 9, 7, 1],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 1, symbol: "add", tile2: 9 },
      { tile1: 10, symbol: "add", tile2: 6 },
      { tile1: 16, symbol: "divide", tile2: 2 },
      { tile1: 8, symbol: "multiply", tile2: 7 },
    ],
  },
  116: {
    bigNumber: 22,
    tiles: [1, 7, 6, 8, 1],
    symbols: { add: 3, subtract: 0, multiply: 0, divide: 1 },
    solution: [
      { tile1: 1, symbol: "add", tile2: 8 },
      { tile1: 9, symbol: "add", tile2: 6 },
      { tile1: 15, symbol: "add", tile2: 7 },
      { tile1: 22, symbol: "divide", tile2: 1 },
    ],
  },
  117: {
    bigNumber: 15,
    tiles: [5, 9, 6, 7, 4],
    symbols: { add: 3, subtract: 0, multiply: 0, divide: 1 },
    solution: [
      { tile1: 7, symbol: "add", tile2: 9 },
      { tile1: 16, symbol: "divide", tile2: 4 },
      { tile1: 4, symbol: "add", tile2: 6 },
      { tile1: 10, symbol: "add", tile2: 5 },
    ],
  },
  118: {
    bigNumber: 15,
    tiles: [6, 3, 2, 9, 2],
    symbols: { add: 3, subtract: 0, multiply: 0, divide: 1 },
    solution: [
      { tile1: 6, symbol: "divide", tile2: 3 },
      { tile1: 2, symbol: "add", tile2: 2 },
      { tile1: 4, symbol: "add", tile2: 2 },
      { tile1: 6, symbol: "add", tile2: 9 },
    ],
  },
  119: {
    bigNumber: 22,
    tiles: [8, 1, 1, 6, 8],
    symbols: { add: 2, subtract: 0, multiply: 0, divide: 2 },
    solution: [
      { tile1: 6, symbol: "add", tile2: 8 },
      { tile1: 14, symbol: "divide", tile2: 1 },
      { tile1: 14, symbol: "add", tile2: 8 },
      { tile1: 22, symbol: "divide", tile2: 1 },
    ],
  },
  120: {
    bigNumber: 34,
    tiles: [3, 9, 9, 2, 2],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 2, symbol: "add", tile2: 3 },
      { tile1: 5, symbol: "multiply", tile2: 9 },
      { tile1: 45, symbol: "subtract", tile2: 2 },
      { tile1: 43, symbol: "subtract", tile2: 9 },
    ],
  },
  121: {
    bigNumber: 50,
    tiles: [5, 3, 2, 1, 5],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 5, symbol: "divide", tile2: 1 },
      { tile1: 5, symbol: "add", tile2: 3 },
      { tile1: 8, symbol: "add", tile2: 2 },
      { tile1: 10, symbol: "multiply", tile2: 5 },
    ],
  },
  122: {
    bigNumber: 7,
    tiles: [4, 5, 8, 8, 3],
    symbols: { add: 3, subtract: 0, multiply: 0, divide: 1 },
    solution: [
      { tile1: 8, symbol: "add", tile2: 4 },
      { tile1: 12, symbol: "add", tile2: 8 },
      { tile1: 20, symbol: "divide", tile2: 5 },
      { tile1: 4, symbol: "add", tile2: 3 },
    ],
  },
  123: {
    bigNumber: 9,
    tiles: [2, 1, 3, 1, 3],
    symbols: { add: 1, subtract: 0, multiply: 1, divide: 2 },
    solution: [
      { tile1: 2, symbol: "multiply", tile2: 3 },
      { tile1: 6, symbol: "add", tile2: 3 },
      { tile1: 9, symbol: "divide", tile2: 1 },
      { tile1: 9, symbol: "divide", tile2: 1 },
    ],
  },
  124: {
    bigNumber: 10,
    tiles: [2, 7, 4, 4, 1],
    symbols: { add: 0, subtract: 2, multiply: 2, divide: 0 },
    solution: [
      { tile1: 7, symbol: "subtract", tile2: 4 },
      { tile1: 3, symbol: "multiply", tile2: 4 },
      { tile1: 12, symbol: "subtract", tile2: 2 },
      { tile1: 10, symbol: "multiply", tile2: 1 },
    ],
  },
  125: {
    bigNumber: 27,
    tiles: [3, 4, 8, 8, 1],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      { tile1: 4, symbol: "multiply", tile2: 1 },
      { tile1: 4, symbol: "multiply", tile2: 8 },
      { tile1: 32, symbol: "add", tile2: 3 },
      { tile1: 35, symbol: "subtract", tile2: 8 },
    ],
  },
  126: {
    bigNumber: 9,
    tiles: [3, 5, 7, 2, 9],
    symbols: { add: 2, subtract: 1, multiply: 0, divide: 1 },
    solution: [
      { tile1: 5, symbol: "add", tile2: 9 },
      { tile1: 14, symbol: "add", tile2: 7 },
      { tile1: 21, symbol: "subtract", tile2: 3 },
      { tile1: 18, symbol: "divide", tile2: 2 },
    ],
  },
  127: {
    bigNumber: 56,
    tiles: [1, 5, 7, 7, 2],
    symbols: { add: 0, subtract: 2, multiply: 2, divide: 0 },
    solution: [
      { tile1: 2, symbol: "multiply", tile2: 5 },
      { tile1: 10, symbol: "subtract", tile2: 1 },
      { tile1: 9, symbol: "multiply", tile2: 7 },
      { tile1: 63, symbol: "subtract", tile2: 7 },
    ],
  },
  128: {
    bigNumber: 19,
    tiles: [5, 9, 8, 8, 5],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 8, symbol: "divide", tile2: 8 },
      { tile1: 1, symbol: "multiply", tile2: 9 },
      { tile1: 9, symbol: "add", tile2: 5 },
      { tile1: 14, symbol: "add", tile2: 5 },
    ],
  },
  129: {
    bigNumber: 90,
    tiles: [1, 5, 2, 8, 1],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      { tile1: 1, symbol: "add", tile2: 8 },
      { tile1: 9, symbol: "multiply", tile2: 5 },
      { tile1: 45, symbol: "multiply", tile2: 2 },
      { tile1: 90, symbol: "divide", tile2: 1 },
    ],
  },
  130: {
    bigNumber: 16,
    tiles: [2, 8, 4, 2, 8],
    symbols: { add: 3, subtract: 0, multiply: 0, divide: 1 },
    solution: [
      { tile1: 8, symbol: "add", tile2: 4 },
      { tile1: 12, symbol: "divide", tile2: 2 },
      { tile1: 6, symbol: "add", tile2: 8 },
      { tile1: 14, symbol: "add", tile2: 2 },
    ],
  },
  131: {
    bigNumber: 77,
    tiles: [2, 5, 8, 9, 6],
    symbols: { add: 0, subtract: 2, multiply: 2, divide: 0 },
    solution: [
      { tile1: 6, symbol: "multiply", tile2: 8 },
      { tile1: 48, symbol: "subtract", tile2: 5 },
      { tile1: 43, symbol: "multiply", tile2: 2 },
      { tile1: 86, symbol: "subtract", tile2: 9 },
    ],
  },
  132: {
    bigNumber: 42,
    tiles: [3, 5, 3, 1, 8],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 5, symbol: "add", tile2: 8 },
      { tile1: 13, symbol: "multiply", tile2: 3 },
      { tile1: 39, symbol: "divide", tile2: 1 },
      { tile1: 39, symbol: "add", tile2: 3 },
    ],
  },
  133: {
    bigNumber: 13,
    tiles: [1, 4, 8, 5, 4],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 8, symbol: "subtract", tile2: 4 },
      { tile1: 4, symbol: "add", tile2: 4 },
      { tile1: 8, symbol: "add", tile2: 5 },
      { tile1: 13, symbol: "multiply", tile2: 1 },
    ],
  },
  134: {
    bigNumber: 36,
    tiles: [8, 4, 4, 5, 5],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 4, symbol: "multiply", tile2: 8 },
      { tile1: 32, symbol: "add", tile2: 5 },
      { tile1: 37, symbol: "add", tile2: 4 },
      { tile1: 41, symbol: "subtract", tile2: 5 },
    ],
  },
  135: {
    bigNumber: 26,
    tiles: [5, 1, 6, 9, 4],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 9, symbol: "multiply", tile2: 4 },
      { tile1: 36, symbol: "add", tile2: 1 },
      { tile1: 37, symbol: "subtract", tile2: 5 },
      { tile1: 32, symbol: "subtract", tile2: 6 },
    ],
  },
  136: {
    bigNumber: 6,
    tiles: [1, 7, 9, 2, 4],
    symbols: { add: 2, subtract: 1, multiply: 0, divide: 1 },
    solution: [
      { tile1: 9, symbol: "subtract", tile2: 2 },
      { tile1: 7, symbol: "divide", tile2: 7 },
      { tile1: 1, symbol: "add", tile2: 1 },
      { tile1: 2, symbol: "add", tile2: 4 },
    ],
  },
  137: {
    bigNumber: 27,
    tiles: [9, 7, 5, 5, 5],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 5, symbol: "divide", tile2: 5 },
      { tile1: 1, symbol: "add", tile2: 7 },
      { tile1: 8, symbol: "subtract", tile2: 5 },
      { tile1: 3, symbol: "multiply", tile2: 9 },
    ],
  },
  138: {
    bigNumber: 7,
    tiles: [1, 7, 1, 1, 2],
    symbols: { add: 0, subtract: 1, multiply: 3, divide: 0 },
    solution: [
      { tile1: 2, symbol: "subtract", tile2: 1 },
      { tile1: 1, symbol: "multiply", tile2: 1 },
      { tile1: 1, symbol: "multiply", tile2: 1 },
      { tile1: 1, symbol: "multiply", tile2: 7 },
    ],
  },
  139: {
    bigNumber: 32,
    tiles: [9, 4, 8, 2, 2],
    symbols: { add: 0, subtract: 1, multiply: 2, divide: 1 },
    solution: [
      { tile1: 8, symbol: "divide", tile2: 4 },
      { tile1: 2, symbol: "multiply", tile2: 9 },
      { tile1: 18, symbol: "subtract", tile2: 2 },
      { tile1: 16, symbol: "multiply", tile2: 2 },
    ],
  },
  140: {
    bigNumber: 31,
    tiles: [7, 9, 5, 1, 6],
    symbols: { add: 0, subtract: 3, multiply: 1, divide: 0 },
    solution: [
      { tile1: 5, symbol: "multiply", tile2: 9 },
      { tile1: 45, symbol: "subtract", tile2: 7 },
      { tile1: 38, symbol: "subtract", tile2: 1 },
      { tile1: 37, symbol: "subtract", tile2: 6 },
    ],
  },
  141: {
    bigNumber: 57,
    tiles: [7, 7, 2, 3, 3],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      { tile1: 2, symbol: "add", tile2: 7 },
      { tile1: 9, symbol: "add", tile2: 3 },
      { tile1: 12, symbol: "add", tile2: 7 },
      { tile1: 19, symbol: "multiply", tile2: 3 },
    ],
  },
  142: {
    bigNumber: 9,
    tiles: [9, 1, 5, 5, 1],
    symbols: { add: 0, subtract: 0, multiply: 1, divide: 3 },
    solution: [
      { tile1: 5, symbol: "divide", tile2: 1 },
      { tile1: 5, symbol: "divide", tile2: 1 },
      { tile1: 5, symbol: "divide", tile2: 5 },
      { tile1: 1, symbol: "multiply", tile2: 9 },
    ],
  },
  143: {
    bigNumber: 14,
    tiles: [1, 2, 6, 5, 7],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      { tile1: 2, symbol: "multiply", tile2: 1 },
      { tile1: 2, symbol: "multiply", tile2: 6 },
      { tile1: 12, symbol: "subtract", tile2: 5 },
      { tile1: 7, symbol: "add", tile2: 7 },
    ],
  },
  144: {
    bigNumber: 8,
    tiles: [2, 4, 2, 9, 6],
    symbols: { add: 1, subtract: 2, multiply: 0, divide: 1 },
    solution: [
      { tile1: 6, symbol: "subtract", tile2: 4 },
      { tile1: 2, symbol: "divide", tile2: 2 },
      { tile1: 1, symbol: "add", tile2: 9 },
      { tile1: 10, symbol: "subtract", tile2: 2 },
    ],
  },
  145: {
    bigNumber: 80,
    tiles: [4, 3, 7, 2, 8],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      { tile1: 7, symbol: "add", tile2: 2 },
      { tile1: 9, symbol: "add", tile2: 8 },
      { tile1: 17, symbol: "add", tile2: 3 },
      { tile1: 20, symbol: "multiply", tile2: 4 },
    ],
  },
  146: {
    bigNumber: 16,
    tiles: [8, 6, 4, 4, 4],
    symbols: { add: 3, subtract: 0, multiply: 0, divide: 1 },
    solution: [
      { tile1: 8, symbol: "divide", tile2: 4 },
      { tile1: 2, symbol: "add", tile2: 4 },
      { tile1: 6, symbol: "add", tile2: 6 },
      { tile1: 12, symbol: "add", tile2: 4 },
    ],
  },
  147: {
    bigNumber: 24,
    tiles: [5, 2, 6, 9, 4],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 2, symbol: "add", tile2: 5 },
      { tile1: 7, symbol: "add", tile2: 9 },
      { tile1: 16, symbol: "multiply", tile2: 6 },
      { tile1: 96, symbol: "divide", tile2: 4 },
    ],
  },
  148: {
    bigNumber: 72,
    tiles: [1, 6, 6, 7, 9],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 1, symbol: "add", tile2: 6 },
      { tile1: 7, symbol: "subtract", tile2: 6 },
      { tile1: 1, symbol: "add", tile2: 7 },
      { tile1: 8, symbol: "multiply", tile2: 9 },
    ],
  },
  149: {
    bigNumber: 3,
    tiles: [6, 1, 1, 1, 7],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 1, symbol: "multiply", tile2: 1 },
      { tile1: 1, symbol: "add", tile2: 1 },
      { tile1: 2, symbol: "add", tile2: 7 },
      { tile1: 9, symbol: "subtract", tile2: 6 },
    ],
  },
  150: {
    bigNumber: 9,
    tiles: [5, 6, 6, 8, 6],
    symbols: { add: 2, subtract: 0, multiply: 0, divide: 2 },
    solution: [
      { tile1: 6, symbol: "divide", tile2: 6 },
      { tile1: 1, symbol: "add", tile2: 5 },
      { tile1: 6, symbol: "divide", tile2: 6 },
      { tile1: 1, symbol: "add", tile2: 8 },
    ],
  },
  151: {
    bigNumber: 43,
    tiles: [7, 9, 9, 4, 9],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 9, symbol: "multiply", tile2: 4 },
      { tile1: 36, symbol: "subtract", tile2: 9 },
      { tile1: 27, symbol: "add", tile2: 7 },
      { tile1: 34, symbol: "add", tile2: 9 },
    ],
  },
  152: {
    bigNumber: 62,
    tiles: [6, 1, 3, 2, 7],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 3, symbol: "add", tile2: 7 },
      { tile1: 10, symbol: "divide", tile2: 1 },
      { tile1: 10, symbol: "multiply", tile2: 6 },
      { tile1: 60, symbol: "add", tile2: 2 },
    ],
  },
  153: {
    bigNumber: 1,
    tiles: [7, 8, 3, 3, 6],
    symbols: { add: 2, subtract: 0, multiply: 0, divide: 2 },
    solution: [
      { tile1: 3, symbol: "add", tile2: 7 },
      { tile1: 10, symbol: "add", tile2: 8 },
      { tile1: 18, symbol: "divide", tile2: 6 },
      { tile1: 3, symbol: "divide", tile2: 3 },
    ],
  },
  154: {
    bigNumber: 64,
    tiles: [2, 2, 2, 6, 9],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      { tile1: 9, symbol: "add", tile2: 6 },
      { tile1: 15, symbol: "multiply", tile2: 2 },
      { tile1: 30, symbol: "add", tile2: 2 },
      { tile1: 32, symbol: "multiply", tile2: 2 },
    ],
  },
  155: {
    bigNumber: 12,
    tiles: [4, 6, 3, 6, 9],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 9, symbol: "add", tile2: 6 },
      { tile1: 15, symbol: "add", tile2: 3 },
      { tile1: 18, symbol: "divide", tile2: 6 },
      { tile1: 3, symbol: "multiply", tile2: 4 },
    ],
  },
  156: {
    bigNumber: 58,
    tiles: [9, 4, 3, 2, 1],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      { tile1: 9, symbol: "divide", tile2: 1 },
      { tile1: 9, symbol: "multiply", tile2: 3 },
      { tile1: 27, symbol: "multiply", tile2: 2 },
      { tile1: 54, symbol: "add", tile2: 4 },
    ],
  },
  157: {
    bigNumber: 14,
    tiles: [7, 2, 2, 4, 2],
    symbols: { add: 0, subtract: 0, multiply: 3, divide: 1 },
    solution: [
      { tile1: 2, symbol: "multiply", tile2: 7 },
      { tile1: 14, symbol: "multiply", tile2: 2 },
      { tile1: 28, symbol: "multiply", tile2: 2 },
      { tile1: 56, symbol: "divide", tile2: 4 },
    ],
  },
  158: {
    bigNumber: 17,
    tiles: [1, 3, 2, 2, 7],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 3, symbol: "add", tile2: 2 },
      { tile1: 5, symbol: "multiply", tile2: 7 },
      { tile1: 35, symbol: "subtract", tile2: 1 },
      { tile1: 34, symbol: "divide", tile2: 2 },
    ],
  },
  159: {
    bigNumber: 4,
    tiles: [3, 9, 2, 3, 7],
    symbols: { add: 2, subtract: 2, multiply: 0, divide: 0 },
    solution: [
      { tile1: 3, symbol: "add", tile2: 2 },
      { tile1: 5, symbol: "add", tile2: 9 },
      { tile1: 14, symbol: "subtract", tile2: 3 },
      { tile1: 11, symbol: "subtract", tile2: 7 },
    ],
  },
  160: {
    bigNumber: 32,
    tiles: [1, 1, 2, 8, 7],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 1, symbol: "add", tile2: 8 },
      { tile1: 9, symbol: "multiply", tile2: 7 },
      { tile1: 63, symbol: "add", tile2: 1 },
      { tile1: 64, symbol: "divide", tile2: 2 },
    ],
  },
  161: {
    bigNumber: 42,
    tiles: [7, 3, 2, 7, 1],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 2, symbol: "divide", tile2: 1 },
      { tile1: 2, symbol: "add", tile2: 7 },
      { tile1: 9, symbol: "subtract", tile2: 3 },
      { tile1: 6, symbol: "multiply", tile2: 7 },
    ],
  },
  162: {
    bigNumber: 27,
    tiles: [3, 1, 1, 1, 9],
    symbols: { add: 1, subtract: 1, multiply: 2, divide: 0 },
    solution: [
      { tile1: 1, symbol: "multiply", tile2: 9 },
      { tile1: 9, symbol: "add", tile2: 1 },
      { tile1: 10, symbol: "subtract", tile2: 1 },
      { tile1: 9, symbol: "multiply", tile2: 3 },
    ],
  },
  163: {
    bigNumber: 7,
    tiles: [9, 6, 5, 9, 1],
    symbols: { add: 1, subtract: 2, multiply: 0, divide: 1 },
    solution: [
      { tile1: 9, symbol: "subtract", tile2: 5 },
      { tile1: 4, symbol: "add", tile2: 9 },
      { tile1: 13, symbol: "subtract", tile2: 6 },
      { tile1: 7, symbol: "divide", tile2: 1 },
    ],
  },
  164: {
    bigNumber: 25,
    tiles: [8, 3, 9, 3, 3],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 3, symbol: "multiply", tile2: 9 },
      { tile1: 27, symbol: "add", tile2: 3 },
      { tile1: 30, symbol: "add", tile2: 3 },
      { tile1: 33, symbol: "subtract", tile2: 8 },
    ],
  },
  165: {
    bigNumber: 22,
    tiles: [4, 3, 2, 6, 7],
    symbols: { add: 4, subtract: 0, multiply: 0, divide: 0 },
    solution: [
      { tile1: 3, symbol: "add", tile2: 6 },
      { tile1: 9, symbol: "add", tile2: 2 },
      { tile1: 11, symbol: "add", tile2: 7 },
      { tile1: 18, symbol: "add", tile2: 4 },
    ],
  },
  166: {
    bigNumber: 2,
    tiles: [6, 4, 6, 2, 4],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 4, symbol: "divide", tile2: 4 },
      { tile1: 1, symbol: "add", tile2: 6 },
      { tile1: 7, symbol: "subtract", tile2: 6 },
      { tile1: 1, symbol: "multiply", tile2: 2 },
    ],
  },
  167: {
    bigNumber: 8,
    tiles: [1, 9, 3, 8, 3],
    symbols: { add: 0, subtract: 0, multiply: 1, divide: 3 },
    solution: [
      { tile1: 9, symbol: "divide", tile2: 3 },
      { tile1: 3, symbol: "divide", tile2: 3 },
      { tile1: 1, symbol: "divide", tile2: 1 },
      { tile1: 1, symbol: "multiply", tile2: 8 },
    ],
  },
  168: {
    bigNumber: 8,
    tiles: [8, 4, 1, 2, 2],
    symbols: { add: 1, subtract: 0, multiply: 1, divide: 2 },
    solution: [
      { tile1: 2, symbol: "multiply", tile2: 4 },
      { tile1: 8, symbol: "add", tile2: 8 },
      { tile1: 16, symbol: "divide", tile2: 1 },
      { tile1: 16, symbol: "divide", tile2: 2 },
    ],
  },
  169: {
    bigNumber: 51,
    tiles: [7, 3, 4, 6, 2],
    symbols: { add: 3, subtract: 0, multiply: 1, divide: 0 },
    solution: [
      { tile1: 2, symbol: "add", tile2: 6 },
      { tile1: 8, symbol: "add", tile2: 3 },
      { tile1: 11, symbol: "multiply", tile2: 4 },
      { tile1: 44, symbol: "add", tile2: 7 },
    ],
  },
  170: {
    bigNumber: 32,
    tiles: [2, 4, 4, 8, 2],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 4, symbol: "subtract", tile2: 2 },
      { tile1: 2, symbol: "add", tile2: 8 },
      { tile1: 10, symbol: "subtract", tile2: 2 },
      { tile1: 8, symbol: "multiply", tile2: 4 },
    ],
  },
  171: {
    bigNumber: 10,
    tiles: [1, 7, 4, 6, 6],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 7, symbol: "add", tile2: 4 },
      { tile1: 11, symbol: "subtract", tile2: 1 },
      { tile1: 10, symbol: "multiply", tile2: 6 },
      { tile1: 60, symbol: "divide", tile2: 6 },
    ],
  },
  172: {
    bigNumber: 4,
    tiles: [4, 6, 1, 8, 2],
    symbols: { add: 2, subtract: 0, multiply: 0, divide: 2 },
    solution: [
      { tile1: 4, symbol: "divide", tile2: 1 },
      { tile1: 4, symbol: "add", tile2: 8 },
      { tile1: 12, symbol: "divide", tile2: 6 },
      { tile1: 2, symbol: "add", tile2: 2 },
    ],
  },
  173: {
    bigNumber: 47,
    tiles: [5, 6, 1, 1, 6],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      { tile1: 6, symbol: "add", tile2: 1 },
      { tile1: 7, symbol: "multiply", tile2: 1 },
      { tile1: 7, symbol: "multiply", tile2: 6 },
      { tile1: 42, symbol: "add", tile2: 5 },
    ],
  },
  174: {
    bigNumber: 19,
    tiles: [4, 2, 4, 1, 8],
    symbols: { add: 4, subtract: 0, multiply: 0, divide: 0 },
    solution: [
      { tile1: 1, symbol: "add", tile2: 8 },
      { tile1: 9, symbol: "add", tile2: 4 },
      { tile1: 13, symbol: "add", tile2: 2 },
      { tile1: 15, symbol: "add", tile2: 4 },
    ],
  },
  175: {
    bigNumber: 50,
    tiles: [2, 1, 4, 6, 6],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 2, symbol: "add", tile2: 1 },
      { tile1: 3, symbol: "add", tile2: 6 },
      { tile1: 9, symbol: "multiply", tile2: 6 },
      { tile1: 54, symbol: "subtract", tile2: 4 },
    ],
  },
  176: {
    bigNumber: 2,
    tiles: [3, 2, 1, 8, 9],
    symbols: { add: 1, subtract: 1, multiply: 0, divide: 2 },
    solution: [
      { tile1: 3, symbol: "add", tile2: 9 },
      { tile1: 12, symbol: "subtract", tile2: 8 },
      { tile1: 4, symbol: "divide", tile2: 2 },
      { tile1: 2, symbol: "divide", tile2: 1 },
    ],
  },
  177: {
    bigNumber: 56,
    tiles: [2, 1, 1, 8, 6],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 2, symbol: "add", tile2: 6 },
      { tile1: 8, symbol: "subtract", tile2: 1 },
      { tile1: 7, symbol: "multiply", tile2: 8 },
      { tile1: 56, symbol: "divide", tile2: 1 },
    ],
  },
  178: {
    bigNumber: 18,
    tiles: [3, 9, 6, 3, 8],
    symbols: { add: 2, subtract: 0, multiply: 1, divide: 1 },
    solution: [
      { tile1: 9, symbol: "multiply", tile2: 8 },
      { tile1: 72, symbol: "divide", tile2: 6 },
      { tile1: 12, symbol: "add", tile2: 3 },
      { tile1: 15, symbol: "add", tile2: 3 },
    ],
  },
  179: {
    bigNumber: 12,
    tiles: [3, 4, 1, 6, 2],
    symbols: { add: 3, subtract: 1, multiply: 0, divide: 0 },
    solution: [
      { tile1: 1, symbol: "add", tile2: 3 },
      { tile1: 4, symbol: "add", tile2: 4 },
      { tile1: 8, symbol: "add", tile2: 6 },
      { tile1: 14, symbol: "subtract", tile2: 2 },
    ],
  },
  180: {
    bigNumber: 63,
    tiles: [1, 4, 9, 3, 8],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      { tile1: 8, symbol: "add", tile2: 9 },
      { tile1: 17, symbol: "multiply", tile2: 1 },
      { tile1: 17, symbol: "add", tile2: 4 },
      { tile1: 21, symbol: "multiply", tile2: 3 },
    ],
  },
  181: {
    bigNumber: 21,
    tiles: [8, 9, 1, 3, 1],
    symbols: { add: 3, subtract: 0, multiply: 0, divide: 1 },
    solution: [
      { tile1: 1, symbol: "divide", tile2: 1 },
      { tile1: 1, symbol: "add", tile2: 3 },
      { tile1: 4, symbol: "add", tile2: 9 },
      { tile1: 13, symbol: "add", tile2: 8 },
    ],
  },
  182: {
    bigNumber: 42,
    tiles: [2, 5, 5, 8, 1],
    symbols: { add: 0, subtract: 1, multiply: 2, divide: 1 },
    solution: [
      { tile1: 5, symbol: "divide", tile2: 1 },
      { tile1: 5, symbol: "multiply", tile2: 5 },
      { tile1: 25, symbol: "multiply", tile2: 2 },
      { tile1: 50, symbol: "subtract", tile2: 8 },
    ],
  },
  183: {
    bigNumber: 11,
    tiles: [2, 2, 4, 3, 5],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 3, symbol: "multiply", tile2: 5 },
      { tile1: 15, symbol: "subtract", tile2: 2 },
      { tile1: 13, symbol: "subtract", tile2: 4 },
      { tile1: 9, symbol: "add", tile2: 2 },
    ],
  },
  184: {
    bigNumber: 2,
    tiles: [6, 9, 7, 4, 6],
    symbols: { add: 2, subtract: 1, multiply: 0, divide: 1 },
    solution: [
      { tile1: 9, symbol: "add", tile2: 4 },
      { tile1: 13, symbol: "subtract", tile2: 7 },
      { tile1: 6, symbol: "add", tile2: 6 },
      { tile1: 12, symbol: "divide", tile2: 6 },
    ],
  },
  185: {
    bigNumber: 77,
    tiles: [3, 7, 8, 8, 8],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      { tile1: 8, symbol: "divide", tile2: 8 },
      { tile1: 1, symbol: "multiply", tile2: 3 },
      { tile1: 3, symbol: "add", tile2: 8 },
      { tile1: 11, symbol: "multiply", tile2: 7 },
    ],
  },
  186: {
    bigNumber: 13,
    tiles: [9, 1, 3, 5, 5],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 1, symbol: "add", tile2: 5 },
      { tile1: 6, symbol: "divide", tile2: 3 },
      { tile1: 2, symbol: "multiply", tile2: 9 },
      { tile1: 18, symbol: "subtract", tile2: 5 },
    ],
  },
  187: {
    bigNumber: 19,
    tiles: [3, 8, 3, 4, 5],
    symbols: { add: 0, subtract: 2, multiply: 2, divide: 0 },
    solution: [
      { tile1: 4, symbol: "subtract", tile2: 3 },
      { tile1: 1, symbol: "multiply", tile2: 3 },
      { tile1: 3, symbol: "multiply", tile2: 8 },
      { tile1: 24, symbol: "subtract", tile2: 5 },
    ],
  },
  188: {
    bigNumber: 7,
    tiles: [8, 5, 7, 9, 6],
    symbols: { add: 2, subtract: 2, multiply: 0, divide: 0 },
    solution: [
      { tile1: 9, symbol: "add", tile2: 5 },
      { tile1: 14, symbol: "add", tile2: 7 },
      { tile1: 21, symbol: "subtract", tile2: 6 },
      { tile1: 15, symbol: "subtract", tile2: 8 },
    ],
  },
  189: {
    bigNumber: 6,
    tiles: [2, 5, 3, 1, 9],
    symbols: { add: 1, subtract: 1, multiply: 1, divide: 1 },
    solution: [
      { tile1: 9, symbol: "subtract", tile2: 1 },
      { tile1: 8, symbol: "add", tile2: 2 },
      { tile1: 10, symbol: "divide", tile2: 5 },
      { tile1: 2, symbol: "multiply", tile2: 3 },
    ],
  },
  190: {
    bigNumber: 17,
    tiles: [2, 7, 4, 9, 2],
    symbols: { add: 2, subtract: 0, multiply: 0, divide: 2 },
    solution: [
      { tile1: 4, symbol: "divide", tile2: 2 },
      { tile1: 2, symbol: "divide", tile2: 2 },
      { tile1: 1, symbol: "add", tile2: 9 },
      { tile1: 10, symbol: "add", tile2: 7 },
    ],
  },
  191: {
    bigNumber: 46,
    tiles: [5, 1, 3, 4, 2],
    symbols: { add: 1, subtract: 0, multiply: 2, divide: 1 },
    solution: [
      { tile1: 4, symbol: "divide", tile2: 1 },
      { tile1: 4, symbol: "multiply", tile2: 5 },
      { tile1: 20, symbol: "add", tile2: 3 },
      { tile1: 23, symbol: "multiply", tile2: 2 },
    ],
  },
  192: {
    bigNumber: 96,
    tiles: [5, 3, 8, 2, 7],
    symbols: { add: 0, subtract: 2, multiply: 2, divide: 0 },
    solution: [
      { tile1: 7, symbol: "multiply", tile2: 8 },
      { tile1: 56, symbol: "subtract", tile2: 5 },
      { tile1: 51, symbol: "subtract", tile2: 3 },
      { tile1: 48, symbol: "multiply", tile2: 2 },
    ],
  },
  193: {
    bigNumber: 29,
    tiles: [8, 7, 7, 2, 1],
    symbols: { add: 2, subtract: 0, multiply: 2, divide: 0 },
    solution: [
      { tile1: 1, symbol: "multiply", tile2: 7 },
      { tile1: 7, symbol: "multiply", tile2: 2 },
      { tile1: 14, symbol: "add", tile2: 8 },
      { tile1: 22, symbol: "add", tile2: 7 },
    ],
  },
  194: {
    bigNumber: 12,
    tiles: [7, 8, 3, 9, 1],
    symbols: { add: 3, subtract: 1, multiply: 0, divide: 0 },
    solution: [
      { tile1: 1, symbol: "add", tile2: 3 },
      { tile1: 4, symbol: "add", tile2: 9 },
      { tile1: 13, symbol: "subtract", tile2: 8 },
      { tile1: 5, symbol: "add", tile2: 7 },
    ],
  },
  195: {
    bigNumber: 33,
    tiles: [2, 7, 5, 2, 8],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 5, symbol: "multiply", tile2: 8 },
      { tile1: 40, symbol: "subtract", tile2: 7 },
      { tile1: 33, symbol: "subtract", tile2: 2 },
      { tile1: 31, symbol: "add", tile2: 2 },
    ],
  },
  196: {
    bigNumber: 65,
    tiles: [8, 9, 5, 5, 7],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 5, symbol: "add", tile2: 8 },
      { tile1: 13, symbol: "subtract", tile2: 5 },
      { tile1: 8, symbol: "multiply", tile2: 9 },
      { tile1: 72, symbol: "subtract", tile2: 7 },
    ],
  },
  197: {
    bigNumber: 25,
    tiles: [7, 7, 4, 9, 4],
    symbols: { add: 2, subtract: 1, multiply: 1, divide: 0 },
    solution: [
      { tile1: 4, symbol: "add", tile2: 7 },
      { tile1: 11, symbol: "subtract", tile2: 7 },
      { tile1: 4, symbol: "multiply", tile2: 4 },
      { tile1: 16, symbol: "add", tile2: 9 },
    ],
  },
  198: {
    bigNumber: 8,
    tiles: [3, 8, 8, 4, 4],
    symbols: { add: 1, subtract: 2, multiply: 1, divide: 0 },
    solution: [
      { tile1: 4, symbol: "add", tile2: 4 },
      { tile1: 8, symbol: "multiply", tile2: 3 },
      { tile1: 24, symbol: "subtract", tile2: 8 },
      { tile1: 16, symbol: "subtract", tile2: 8 },
    ],
  },
  199: {
    bigNumber: 7,
    tiles: [4, 5, 1, 6, 2],
    symbols: { add: 3, subtract: 0, multiply: 0, divide: 1 },
    solution: [
      { tile1: 4, symbol: "add", tile2: 2 },
      { tile1: 6, symbol: "divide", tile2: 6 },
      { tile1: 1, symbol: "add", tile2: 1 },
      { tile1: 2, symbol: "add", tile2: 5 },
    ],
  },
  200: {
    bigNumber: 1,
    tiles: [1, 7, 9, 2, 4],
    symbols: { add: 2, subtract: 2, multiply: 0, divide: 0 },
    solution: [
      { tile1: 1, symbol: "add", tile2: 4 },
      { tile1: 5, symbol: "subtract", tile2: 2 },
      { tile1: 3, symbol: "add", tile2: 7 },
      { tile1: 10, symbol: "subtract", tile2: 9 },
    ],
  },
};
